import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { expect, it, vi } from 'vitest'
import { createProject, parseProject } from '../src/core/project'
import { newCourseOutline, projectCourse, saveCourseOutline } from '../src/core/course'
import { bindCourseNarration, registerCourseNarration } from '../src/core/courseNarration'
import { applyCourseNarrationPlacement, commitCourseNarrationPlacement, courseNarrationPlacementIsCurrent, reviewCourseNarrationPlacement } from '../src/core/courseNarrationPlacement'
import { commitCourseNarrationRange, courseNarrationRangeIsCurrent, invalidateCourseNarrationRange, reviewCourseNarrationRange } from '../src/core/courseNarrationRange'
import { CourseNarrationRangeControl } from '../src/components/CourseNarrationRangeControl'
import { UiLanguageProvider } from '../src/components/UiLanguageProvider'
import { PersistentVersionHistory } from '../src/core/versioning'
import { uiCourseNarrationRangeMessages } from '../src/core/uiCourseNarrationRangeMessages'
import { translateUi } from '../src/core/uiMessages'
function fixture(){const p=createProject('Range'),course=saveCourseOutline(p,{...newCourseOutline(p),id:'course',language:'en',modules:[{id:'module',title:'Module',lessons:[{id:'lesson',title:'Lesson',objective:'Explain',script:'Authorized words',range:{inMs:1000,outMs:2000}},{id:'other',title:'Other',objective:'Keep',script:'Private other script',range:{inMs:4000,outMs:5000}}]}]}),binding=bindCourseNarration(course,'lesson');return registerCourseNarration(course,{id:'job',adapterId:'piper',voiceId:'KINAOU/Models/test.onnx',state:'succeeded',progress:1,audioPath:'KINAOU/Assets/GeneratedVoice/job.wav',durationMs:2000,sizeBytes:5000,createdAt:'2026-09-27T00:00:00Z',updatedAt:'2026-09-27T00:00:01Z'},binding.script,binding)}
const deps=()=>({snapshot:vi.fn(),persist:vi.fn()})
const inspect=(p=fixture())=>reviewCourseNarrationRange(p,p.assets[0].id)
it('extends exactly one end using full measured duration, without changing anything else or auto-placement',()=>{
 const p=fixture(),before=JSON.stringify(p),r=inspect(p),d=deps();expect(r).toMatchObject({startMs:1000,previousEndMs:2000,endMs:3000,durationMs:2000,sourceRevision:1,currentRevision:1});expect(Object.isFrozen(r)).toBe(true)
 const next=commitCourseNarrationRange(p,r,true,d),oldCourse=projectCourse(p)!,newCourse=projectCourse(next)!;expect(newCourse.revision).toBe(2);expect(newCourse.modules[0].lessons[0]).toEqual({...oldCourse.modules[0].lessons[0],range:{inMs:1000,outMs:3000}});expect(newCourse.modules[0].lessons[1]).toEqual(oldCourse.modules[0].lessons[1]);expect(next.assets).toEqual(p.assets);expect(next.tracks).toEqual(p.tracks);expect(next.script).toBe(p.script);expect(next.storyboard).toEqual(p.storyboard);expect(JSON.stringify(p)).toBe(before);expect(d.snapshot).toHaveBeenCalledExactlyOnceWith(p)
 const reloaded=parseProject(JSON.parse(JSON.stringify(next))),placement=reviewCourseNarrationPlacement(reloaded,p.assets[0].id,null);expect(placement.remainingMs).toBe(0);expect(applyCourseNarrationPlacement(reloaded,placement).tracks.at(-1)!.clips[0]).toMatchObject({startMs:1000,durationMs:2000,speed:1,sourceOffsetMs:0})
})
it('rounds measured fractional milliseconds up rather than cutting the final sample',()=>{const p=fixture();p.assets[0].metadata.durationMs=2000.1;expect(inspect(p).endMs).toBe(3001)})
it('retries one prepared revision and snapshot, then refuses duplicate or forged commits',()=>{const p=fixture(),r=inspect(p),d=deps();expect(()=>commitCourseNarrationRange(p,r,false,d)).toThrow();expect(()=>commitCourseNarrationRange(p,{...r},true,d)).toThrow();d.persist.mockImplementationOnce(()=>{throw Error('disk')});expect(()=>commitCourseNarrationRange(p,r,true,d)).toThrow('disk');const next=commitCourseNarrationRange(p,r,true,d);expect(d.snapshot).toHaveBeenCalledTimes(1);expect(d.persist.mock.calls[0][0]).toBe(next);expect(projectCourse(next)!.revision).toBe(2);expect(()=>commitCourseNarrationRange(p,r,true,d)).toThrow()})
it('snapshot failure precedes persistence and can be retried',()=>{const p=fixture(),r=inspect(p),d=deps();d.snapshot.mockImplementationOnce(()=>{throw Error('history')});expect(()=>commitCourseNarrationRange(p,r,true,d)).toThrow('history');expect(d.persist).not.toHaveBeenCalled();commitCourseNarrationRange(p,r,true,d);expect(d.snapshot).toHaveBeenCalledTimes(2)})
it.each(['project','disabled','explicit'] as const)('permanently invalidates %s transitions including A–B–A',kind=>{const p=fixture(),r=inspect(p);if(kind==='explicit')invalidateCourseNarrationRange(r);else expect(courseNarrationRangeIsCurrent(kind==='project'?{...p,title:'changed'}:p,r,kind==='disabled')).toBe(false);expect(courseNarrationRangeIsCurrent(p,r)).toBe(false);expect(()=>commitCourseNarrationRange(p,r,true,deps())).toThrow()})
it.each([0,-1,NaN,Infinity,'2000',86400001])('refuses invalid recorded duration %s',duration=>{const p=fixture();p.assets[0].metadata.durationMs=duration;expect(()=>inspect(p)).toThrow('duration')})
it('does not shrink a range that already fits',()=>{const p=fixture();p.assets[0].metadata.durationMs=1000;expect(()=>inspect(p)).toThrow('notNeeded')})
it('refuses another lesson collision including other modules and 24-hour overflow',()=>{
 const p=fixture(),c=projectCourse(p)!;p.assets[0].metadata.durationMs=3500;expect(()=>inspect(p)).toThrow('collision')
 const moved=saveCourseOutline(p,{...c,modules:[{...c.modules[0],lessons:[c.modules[0].lessons[0]]},{id:'second',title:'Second',lessons:[c.modules[0].lessons[1]]}]});expect(()=>inspect(moved)).toThrow('collision')
 const huge=fixture();huge.assets[0].metadata.durationMs=86400000;expect(()=>inspect(huge)).toThrow('boundary')
})
it.each(['source','script','language','offline','kind','path','duplicateAsset','placed'] as const)('refuses %s identity or availability problems',kind=>{let p=fixture();if(kind==='source')delete p.assets[0].metadata.courseNarrationSource;if(kind==='script'){const c=projectCourse(p)!;c.modules[0].lessons[0].script='Changed';p=saveCourseOutline(p,c)}if(kind==='language'){const c=projectCourse(p)!;p=saveCourseOutline(p,{...c,language:'fr'})}if(kind==='offline')p.assets[0].offline=true;if(kind==='kind')p.assets[0].kind='video';if(kind==='path')p.assets[0].uri='KINAOU/Assets/../private.wav';if(kind==='duplicateAsset')p.assets.push(p.assets[0]);if(kind==='placed')p.tracks.push({id:'muted',type:'voice',name:'Muted',muted:true,locked:false,clips:[{id:'used',assetId:p.assets[0].id,startMs:8000,durationMs:2000,sourceOffsetMs:0,gain:1,speed:1}]});expect(()=>inspect(p)).toThrow()})
it('safety history restores only project references and the original lesson bounds',()=>{const p=fixture(),memory=new Map<string,string>(),history=new PersistentVersionHistory({getItem:k=>memory.get(k)??null,setItem:(k,v)=>{memory.set(k,v)},removeItem:k=>{memory.delete(k)}}),next=commitCourseNarrationRange(p,inspect(p),true,{snapshot:value=>{history.snapshot(value,'Before extending lesson for full narration','system')},persist:()=>{}}),restored=history.restoreReversibly(next,history.list(p.id)[0].id).project;expect(projectCourse(restored)).toEqual(projectCourse(p));expect(restored.assets).toEqual(p.assets)})
it('placement now permanently rejects observed project A–B–A',()=>{const p=fixture(),next=commitCourseNarrationRange(p,inspect(p),true,deps()),r=reviewCourseNarrationPlacement(next,p.assets[0].id,null);expect(courseNarrationPlacementIsCurrent({...next,title:'changed'},r)).toBe(false);expect(courseNarrationPlacementIsCurrent(next,r)).toBe(false);expect(()=>commitCourseNarrationPlacement(next,r,deps())).toThrow()})
it('subsequent placement retries identical track/clip IDs and one snapshot',()=>{const p=fixture(),next=commitCourseNarrationRange(p,inspect(p),true,deps()),r=reviewCourseNarrationPlacement(next,p.assets[0].id,null),d=deps();d.persist.mockImplementationOnce(()=>{throw Error('disk')});expect(()=>commitCourseNarrationPlacement(next,r,d)).toThrow('disk');const placed=commitCourseNarrationPlacement(next,r,d);expect(d.persist.mock.calls[0][0]).toBe(placed);expect(d.snapshot).toHaveBeenCalledTimes(1);expect(placed.tracks.at(-1)!.clips).toHaveLength(1);expect(()=>commitCourseNarrationPlacement(next,r,d)).toThrow()})
it.each(['de','en','fr'] as const)('renders %s controls with no I/O or automatic writes',language=>{const p=fixture(),write=vi.fn(),fetch=vi.spyOn(globalThis,'fetch');try{const html=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:language,children:createElement(CourseNarrationRangeControl,{project:p,asset:p.assets[0],history:new PersistentVersionHistory({getItem:()=>null,setItem:write,removeItem:write}),onProjectChange:write})}));expect(html).toContain(translateUi(language,'course.voiceRange.heading'));for(const key of Object.keys(uiCourseNarrationRangeMessages) as Array<keyof typeof uiCourseNarrationRangeMessages>)expect(translateUi(language,key)).not.toBe(key);expect(fetch).not.toHaveBeenCalled();expect(write).not.toHaveBeenCalled()}finally{fetch.mockRestore()}})
