import {it,expect,vi} from 'vitest'
import {createElement} from 'react'
import {renderToStaticMarkup} from 'react-dom/server'
import {createProject} from '../src/core/project'
import {newCourseOutline,saveCourseOutline} from '../src/core/course'
import {recordSuccessfulExport,projectCourseOutputIndex} from '../src/core/exportHistory'
import {createCourseOutputNavigation,resolveCourseOutputNavigation,courseOutputNavigationIsCurrent} from '../src/core/courseOutputNavigation'
import {CourseOutputFileCheckPanel} from '../src/components/CourseOutputFileCheckPanel'
import {CourseProductionOverviewPanel} from '../src/components/CourseProductionOverviewPanel'
import {UiLanguageProvider} from '../src/components/UiLanguageProvider'
import {translateUi} from '../src/core/uiMessages'
import {CourseOutputPlayback} from '../src/core/courseOutputPlayback'
function fixture(){let p=createProject('Navigation');p=saveCourseOutline(p,{...newCourseOutline(p),id:'course',modules:[{id:'new-module',title:'Current module',lessons:[{id:'lesson',title:'Current lesson',script:'PRIVATE_SCRIPT',objective:'PRIVATE_OBJECTIVE',range:{inMs:1000,outMs:3000}},{id:'other',title:'Other lesson',objective:'',range:{inMs:3000,outMs:4000}},{id:'empty',title:'No exports',objective:'',range:{inMs:4000,outMs:5000}}]}]});for(const [jobId,day,courseId,lessonId] of [['old',1,'course','lesson'],['new',2,'course','lesson'],['other',3,'course','other'],['foreign',4,'foreign','lesson']] as const)p=recordSuccessfulExport(p,{jobId,label:jobId,outputRelativePath:`KINAOU/Renders/${jobId}.mp4`,format:'landscape',range:{inMs:0,outMs:1000},durationMs:1000,sceneIds:[],completedAt:`2026-10-0${day}T00:00:00Z`,courseLesson:{courseId,moduleId:'old-module',lessonId,outlineRevision:1,courseTitle:'Historical course',moduleTitle:'Historical module',lessonTitle:`Historical ${jobId}`,language:'fr'}});return p}
it('binds stable lesson/course identities, sorts newest first and preserves historical fields and private project data',()=>{const p=fixture(),before=JSON.stringify(p),nav=createCourseOutputNavigation(p,'lesson');expect(Object.isFrozen(nav)).toBe(true);expect(nav.label).toBe('Current module / Current lesson');expect(JSON.stringify(nav)).not.toContain('PRIVATE_');const rows=resolveCourseOutputNavigation(p,nav);expect(rows.map(r=>r.jobId)).toEqual(['new','old']);expect(rows[0].courseLesson).toMatchObject({moduleId:'old-module',lessonTitle:'Historical new',language:'fr'});expect(rows[0].range).toEqual({inMs:0,outMs:1000});rows[0].label='Modified copy';expect(resolveCourseOutputNavigation(p,nav)[0].label).toBe('new');expect(JSON.stringify(p)).toBe(before)})
it.each(['missing','empty'])('refuses %s lesson instead of falling back to another output',id=>expect(()=>createCourseOutputNavigation(fixture(),id)).toThrow())
it.each(['project','dirty','receipt'] as const)('permanently invalidates observed %s A–B–A',kind=>{const p=fixture(),nav=createCourseOutputNavigation(p,'lesson'),changed=structuredClone(p);if(kind==='project')changed.title='Other';if(kind==='receipt')(changed.metadata.courseOutputIndex as any).receipts[0].label='Other';expect(courseOutputNavigationIsCurrent(changed,nav,kind==='dirty')).toBe(false);expect(courseOutputNavigationIsCurrent(p,nav)).toBe(false);expect(()=>resolveCourseOutputNavigation(p,nav)).toThrow('no longer current')})
it('rejects forged/serialized navigation and corrupt ledgers without an empty success',()=>{const p=fixture(),nav=createCourseOutputNavigation(p,'lesson');expect(()=>resolveCourseOutputNavigation(p,{...nav})).toThrow();expect(()=>resolveCourseOutputNavigation(p,JSON.parse(JSON.stringify(nav)))).toThrow();p.metadata.courseOutputIndex={};expect(()=>createCourseOutputNavigation(p,'lesson')).toThrow('Invalid course output index')})
it('allows equal saved project values and keeps all-history navigation independent of current range or missing timeline',()=>{const p=fixture(),nav=createCourseOutputNavigation(p,'lesson');expect(resolveCourseOutputNavigation(structuredClone(p),nav)).toHaveLength(2);expect(p.tracks).toEqual([])})
it.each(['de','en','fr'] as const)('renders %s exact historical choices with no automatic selection/request or private script leakage',language=>{const p=fixture(),nav=createCourseOutputNavigation(p,'lesson'),open=vi.fn(),fetch=vi.spyOn(globalThis,'fetch');try{const html=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:language,children:createElement(CourseOutputFileCheckPanel,{project:p,dirty:false,navigation:nav,onClearNavigation:open,workerConnected:true,workerToken:'test-only',workerUrl:'http://127.0.0.1:43117',workerCapabilities:['publish-preflight','course-output-playback']})}));expect(html).toContain('Historical new');expect(html).toContain('Historical old');expect(html).not.toContain('Historical other');expect(html).not.toContain('Historical foreign');expect(html).not.toContain('PRIVATE_');expect(html).not.toContain('<video');expect(html).toContain('value="" selected=""');expect(html).toContain(translateUi(language,'course.outputNav.all'));expect(open).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled()}finally{fetch.mockRestore()}})
it('shows stale navigation explicitly and never falls back to all references',()=>{const p=fixture(),nav=createCourseOutputNavigation(p,'lesson');courseOutputNavigationIsCurrent({...p,title:'Changed'},nav);const html=renderToStaticMarkup(createElement(CourseOutputFileCheckPanel,{project:p,dirty:false,navigation:nav}));expect(html).toContain('lesson selection is stale');expect(html).not.toContain('Historical new');expect(html).toContain('select disabled=""')})
it('disables dirty/no-export navigation and does not invoke a callback while displaying the overview',()=>{const p=fixture(),open=vi.fn(),html=renderToStaticMarkup(createElement(CourseProductionOverviewPanel,{project:p,dirty:true,onEditLesson:open,onOpenOutputs:open}));expect(html.match(/View retained lesson exports/g)).toHaveLength(3);expect(html.match(/button disabled=""/g)).toHaveLength(6);expect(open).not.toHaveBeenCalled()})
it('switching selection detaches a loaded player and revokes its URL; delayed bytes never revive it',async()=>{const p=fixture(),nav=createCourseOutputNavigation(p,'lesson'),receipt=resolveCourseOutputNavigation(p,nav)[0];let scope={project:p,jobId:receipt.jobId,dirty:false,connection:'test'};const revoke=vi.fn(),publish=vi.fn(),load=vi.fn(async()=>new Blob(['synthetic test bytes'],{type:'video/mp4'}));const task=new CourseOutputPlayback(scope,{environment:()=>scope,load,publish,createUrl:()=> 'blob:test-only',revokeUrl:revoke});expect(load).not.toHaveBeenCalled();await task.load();expect(load).toHaveBeenCalledExactlyOnceWith(receipt,expect.any(AbortSignal));scope={...scope,jobId:''};task.observe(scope);expect(revoke).toHaveBeenCalledExactlyOnceWith('blob:test-only');scope={...scope,jobId:receipt.jobId};task.observe(scope);expect(task.wasDetached).toBe(true);await task.load();expect(load).toHaveBeenCalledTimes(1);expect(projectCourseOutputIndex(p)).toHaveLength(4)})
