import { it, expect, vi } from 'vitest'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createProject } from '../src/core/project'
import { newCourseOutline, projectCourse, saveCourseOutline } from '../src/core/course'
import { commitCourseExercises, courseExerciseContext, courseExerciseReviewIsCurrent, parseCourseExerciseResult, projectCourseExerciseRecords, reviewCourseExercises } from '../src/core/courseExerciseDraft'
import { createCourseMaterialPackage } from '../src/core/courseMaterialPackage'
import { CourseExerciseDraftPanel } from '../src/components/CourseExerciseDraftPanel'
import { UiLanguageProvider } from '../src/components/UiLanguageProvider'
import { PersistentVersionHistory } from '../src/core/versioning'
import { WorkerClient } from '../src/core/workerClient'
import { uiCourseExerciseDraftMessages } from '../src/core/uiCourseExerciseDraftMessages'
import { translateUi } from '../src/core/uiMessages'
const script = 'Un triangle a trois côtés. PRIVATE_SCRIPT_MARKER', existing = { id:'existing', title:'Previous', prompt:'OLD TASK', hint:'Old hint', solution:'PRIVATE_OLD_ANSWER', criteria:'PRIVATE_OLD_CRITERIA' }
const proposal = { exercises: [{ title:'Triangle', prompt:'Combien de côtés possède un triangle ?', hint:'Pensez à sa forme.', solution:'PRIVATE_NEW_ANSWER: trois côtés.', criteria:'PRIVATE_NEW_CRITERIA', sourceQuote:'Un triangle a trois côtés.' }] }, generated = { proposal, modelId:'local', adapterId:'ollama' as const }
function fixture() { const base=createProject('Course');return saveCourseOutline(base,{...newCourseOutline(base),id:'course',language:'fr',modules:[{id:'module',title:'Module',lessons:[{id:'lesson',title:'Triangle',objective:'Explain',script,range:{inMs:1000,outMs:6000},exercises:[existing]},{id:'other',title:'Other',objective:'Do not change',script:'OTHER SCRIPT',range:{inMs:6000,outMs:9000}}]}]}) }
const deps = () => ({ snapshot:vi.fn(),persist:vi.fn() })
function prepare(p=fixture(), accepted=proposal) { return reviewCourseExercises(p,courseExerciseContext(p,'lesson',1),generated,accepted) }
it('only selected saved script and preferences enter model context, not answers, other lessons, media or history',()=>{const p=fixture(),before=JSON.stringify(p),context=courseExerciseContext(p,'lesson',1);expect(context).toMatchObject({script,language:'fr',count:1});expect(JSON.stringify(context)).not.toContain('ANSWER');expect(JSON.stringify(context)).not.toContain('OTHER SCRIPT');expect(JSON.stringify(p)).toBe(before)})
it.each(['missing',''])('requires a saved lesson %s',id=>expect(()=>courseExerciseContext(fixture(),id,1)).toThrow())
it.each([0,4,1.5,NaN])('refuses invalid count %s',count=>expect(()=>courseExerciseContext(fixture(),'lesson',count)).toThrow())
it('refuses empty scripts, excessive source bytes and insufficient slots without truncation or removal',()=>{
 for(const source of ['','界'.repeat(5000)]){const p=fixture(),course=projectCourse(p)!;course.modules[0].lessons[0].script=source;const next=saveCourseOutline(p,course);expect(()=>courseExerciseContext(next,'lesson',1)).toThrow()}
 const p=fixture(),course=projectCourse(p)!;course.modules[0].lessons[0].exercises=Array.from({length:20},(_,i)=>({...existing,id:'e'+i}));expect(()=>courseExerciseContext(saveCourseOutline(p,course),'lesson',1)).toThrow('insufficient room')
})
it.each(['model','adapter','quote','extra','count'] as const)('refuses invalid %s model result',kind=>{const result:any=structuredClone(generated);if(kind==='model')result.modelId='different';if(kind==='adapter')result.adapterId='cloud';if(kind==='quote')result.proposal.exercises[0].sourceQuote='invented';if(kind==='extra')result.approved=true;if(kind==='count')result.proposal.exercises.push({...proposal.exercises[0],prompt:'other'});expect(()=>parseCourseExerciseResult(courseExerciseContext(fixture(),'lesson',1),result,'local')).toThrow()})
it('appends only reviewed edited exercises with unique stable ids and private provenance; preserves all other content',()=>{
 const p=fixture(),before=JSON.stringify(p),accepted={exercises:[{...proposal.exercises[0],hint:'Dessinez la forme.'}]},review=prepare(p,accepted),d=deps(),next=commitCourseExercises(p,review,true,d),course=projectCourse(next)!
 expect(course.revision).toBe(2);expect(course.modules[0].lessons[0].exercises).toHaveLength(2);expect(course.modules[0].lessons[0].exercises![0]).toEqual(existing);expect(course.modules[0].lessons[0].exercises![1]).toMatchObject({hint:accepted.exercises[0].hint,id:review.record.exerciseIds[0]});expect(course.modules[0].lessons[0].exercises![1]).not.toHaveProperty('sourceQuote')
 expect(course.modules[0].lessons[0].script).toBe(script);expect(course.modules[0].lessons[0].range).toEqual({inMs:1000,outMs:6000});expect(course.modules[0].lessons[1]).toEqual(projectCourse(p)!.modules[0].lessons[1]);expect(next.assets).toEqual(p.assets);expect(next.tracks).toEqual(p.tracks);expect(next.script).toBe(p.script);expect(JSON.stringify(p)).toBe(before)
 expect(projectCourseExerciseRecords(next)[0]).toMatchObject({generated:proposal,accepted,edited:true,context:{script}});expect(d.snapshot).toHaveBeenCalledExactlyOnceWith(p);expect(d.persist).toHaveBeenCalledExactlyOnceWith(next);expect(courseExerciseReviewIsCurrent(p,review)).toBe(false)
})
it('failed save retries exact project, ids, revision and snapshot once; a committed review cannot append twice',()=>{
 const p=fixture(),review=prepare(p),d=deps();d.persist.mockImplementationOnce(()=>{throw Error('disk')});expect(()=>commitCourseExercises(p,review,true,d)).toThrow('disk');const next=commitCourseExercises(p,review,true,d);expect(d.persist.mock.calls[0][0]).toBe(next);expect(d.snapshot).toHaveBeenCalledTimes(1);expect(d.persist).toHaveBeenCalledTimes(2);expect(projectCourse(next)!.revision).toBe(2);expect(projectCourse(next)!.modules[0].lessons[0].exercises).toHaveLength(2);expect(()=>commitCourseExercises(p,review,true,d)).toThrow()
})
it('does not persist after failed safety snapshot; retry snapshots successfully before one save',()=>{const p=fixture(),review=prepare(p),d=deps();d.snapshot.mockImplementationOnce(()=>{throw Error('history full')});expect(()=>commitCourseExercises(p,review,true,d)).toThrow();expect(d.persist).not.toHaveBeenCalled();commitCourseExercises(p,review,true,d);expect(d.snapshot).toHaveBeenCalledTimes(2);expect(d.persist).toHaveBeenCalledTimes(1)})
it.each(['project','dirty','record'] as const)('permanently invalidates observed %s A–B–A',kind=>{const p=fixture(),review=prepare(p);if(kind==='record'){review.record.modelId='forged';expect(courseExerciseReviewIsCurrent(p,review)).toBe(false);review.record.modelId='local'}else expect(courseExerciseReviewIsCurrent(kind==='project'?{...p,title:'changed'}:p,review,kind==='dirty')).toBe(false);expect(courseExerciseReviewIsCurrent(p,review)).toBe(false);expect(()=>commitCourseExercises(p,review,true,deps())).toThrow()})
it('requires unchanged context, acknowledgement and authentic review, and refuses existing duplicate normalized prompts',()=>{
 const p=fixture(),review=prepare(p),d=deps();expect(()=>commitCourseExercises(p,review,false,d)).toThrow();expect(()=>commitCourseExercises(p,{...review},true,d)).toThrow();expect(()=>reviewCourseExercises(p,{...courseExerciseContext(p,'lesson',1),script:'changed'},generated,proposal)).toThrow();expect(()=>prepare(p,{exercises:[{...proposal.exercises[0],prompt:'  old  TASK\n'}]})).toThrow('already saved');expect(d.snapshot).not.toHaveBeenCalled()
})
it('keeps previous exercises on a second batch while replacing only latest per-lesson provenance and preserving a safety version',()=>{
 const p=fixture(),d=deps(),next=commitCourseExercises(p,prepare(p),true,d),accepted={exercises:[{...proposal.exercises[0],prompt:'Expliquez la forme du triangle.'}]},again=commitCourseExercises(next,prepare(next,accepted),true,d);expect(projectCourse(again)!.modules[0].lessons[0].exercises).toHaveLength(3);expect(projectCourseExerciseRecords(again)).toHaveLength(1);expect(projectCourseExerciseRecords(again)[0].accepted).toEqual(accepted);expect(d.snapshot.mock.calls[1][0]).toBe(next)
})
it('fails corrupt, duplicate, wrong-project, oversized and forged provenance without silent eviction',()=>{
 const p=fixture(),next=commitCourseExercises(p,prepare(p),true,deps())
 for(const change of [(l:any)=>{l.records[0].projectId='other'},(l:any)=>{l.records.push(l.records[0])},(l:any)=>{l.records[0].edited=true},(l:any)=>{l.records[0].exerciseIds=[]},(l:any)=>{l.records[0].accepted.exercises[0].sourceQuote='made up'}]){const copy=structuredClone(next);change(copy.metadata.courseExerciseDrafts);expect(()=>projectCourseExerciseRecords(copy)).toThrow()}
 const record=projectCourseExerciseRecords(next)[0];record.context.script='x'.repeat(9000);record.generated.exercises[0].sourceQuote='x';record.accepted=structuredClone(record.generated);for(const key of ['prompt','hint','solution','criteria'] as const){record.generated.exercises[0][key]='x'.repeat(1500);record.accepted.exercises[0][key]='x'.repeat(1500)}
 const records=Array.from({length:200},(_,i)=>({...record,context:{...record.context,lessonId:'l'+i},exerciseIds:['e'+i]}));expect(()=>projectCourseExerciseRecords({...p,metadata:{...p.metadata,courseExerciseDrafts:{schemaVersion:1,records}}})).toThrow('4,000,000 bytes')
})
it('exports real learner ZIP/workbook without solution, criteria or provenance, while instructor answer keys retain them',async()=>{
 const p=fixture(),next=commitCourseExercises(p,prepare(p),true,deps()),directory=mkdtempSync(join(tmpdir(),'kinaou-exercise-draft-'))
 try {for(const audience of ['learner','instructor'] as const){const file=await createCourseMaterialPackage(next,audience),target=join(directory,audience+'.zip');writeFileSync(target,file.bytes);execFileSync('unzip',['-t',target]);const paths=execFileSync('unzip',['-Z1',target],{encoding:'utf8'}).trim().split('\n'),read=(path:string)=>execFileSync('unzip',['-p',target,path],{encoding:'utf8'});if(audience==='learner'){for(const path of paths){expect(read(path)).not.toContain('PRIVATE_');expect(read(path)).not.toContain('sourceQuote');expect(read(path)).not.toContain('courseExerciseDrafts')}expect(read('workbook.html')).toContain(proposal.exercises[0].prompt);expect(read('lessons/lesson-lesson/worksheet.txt')).toContain(existing.prompt)}else{expect(read('lessons/lesson-lesson/answer-key.txt')).toContain('PRIVATE_NEW_ANSWER');expect(read('lessons/lesson-lesson/answer-key.txt')).toContain('PRIVATE_NEW_CRITERIA')}}}finally{rmSync(directory,{recursive:true,force:true})}
})
it.each(['de','en','fr'] as const)('renders translated explicit local-only %s UI without requests or writes',language=>{
 const write=vi.fn(),fetch=vi.spyOn(globalThis,'fetch');try{const html=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:language,children:createElement(CourseExerciseDraftPanel,{project:fixture(),lessonId:'lesson',dirty:false,history:new PersistentVersionHistory({getItem:()=>null,setItem:write,removeItem:write}),onProjectChange:write,onSaved:write,workerUrl:'http://127.0.0.1:43117',workerToken:'SECRET',workerConnected:true,workerCapabilities:['course-exercises']})}));expect(html).toContain(translateUi(language,'course.exerciseDraft.heading'));expect(html).not.toContain('SECRET');for(const key of Object.keys(uiCourseExerciseDraftMessages) as Array<keyof typeof uiCourseExerciseDraftMessages>)expect(translateUi(language,key)).not.toBe(key);expect(write).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled()}finally{fetch.mockRestore()}
})
it('uses only the authenticated local exercises route',async()=>{const fetchImpl=vi.fn(async()=>new Response(JSON.stringify({ok:true,type:'course-exercises',result:generated}))),client=new WorkerClient({baseUrl:'http://127.0.0.1:43117',token:'test-only',fetchImpl}),context=courseExerciseContext(fixture(),'lesson',1);expect(await client.generateCourseExercises('local',context)).toEqual(generated);expect(fetchImpl).toHaveBeenCalledWith('http://127.0.0.1:43117/course/exercises/generate',expect.objectContaining({method:'POST',headers:expect.objectContaining({authorization:'Bearer test-only'}),body:JSON.stringify({model:'local',context})}))})
