import {it,expect,vi} from 'vitest'
import {createElement} from 'react'
import {renderToStaticMarkup} from 'react-dom/server'
import {createProject,parseProject} from '../src/core/project'
import {newCourseOutline,saveCourseOutline} from '../src/core/course'
import {courseProductionOverview} from '../src/core/courseProductionOverview'
import {prepareCourseGapPlacement,courseGapPlacementDraft,courseGapPlacementIsCurrent} from '../src/core/courseGapPlacement'
import {reviewCourseDemoPlacement,commitCourseDemoPlacement,parseDemoSeconds} from '../src/core/courseDemoPlacement'
import {CourseDemoPlacementPanel} from '../src/components/CourseDemoPlacementPanel'
import {CourseProductionOverviewPanel} from '../src/components/CourseProductionOverviewPanel'
import {PersistentVersionHistory} from '../src/core/versioning'
import {UiLanguageProvider} from '../src/components/UiLanguageProvider'
import {translateUi} from '../src/core/uiMessages'
function fixture(){const p=parseProject({...createProject('Synthetic gap'),assets:[{id:'image',kind:'image',managed:true,uri:'KINAOU/Assets/image.png',metadata:{}}],tracks:[{id:'visual',type:'image',name:'Existing',clips:[{id:'existing',assetId:'image',startMs:2000,durationMs:1250,sourceOffsetMs:0,speed:1,gain:1}]}]});return saveCourseOutline(p,{...newCourseOutline(p),modules:[{id:'module',title:'Original module',lessons:[{id:'lesson',title:'Original lesson',objective:'Private objective',script:'Private script',range:{inMs:2000,outMs:5000},demonstrations:[{id:'demo',title:'Original demo',steps:'Private steps',expected:'Example',observed:'Unverified',evidence:{assetId:'image',kind:'image',uri:'KINAOU/Assets/image.png'}}]}]}]})}
const gap={startMs:1250,endMs:3000}
it('prepares an immutable exact gap without source selection or writes and still requires normal reviewed placement',()=>{
 const p=fixture(),before=JSON.stringify(p),value=prepareCourseGapPlacement(p,'lesson',gap,'en');expect(Object.isFrozen(value)).toBe(true);expect(value).toEqual({lessonId:'lesson',label:'1.1 · Original module / Original lesson',lessonOffsetMs:1250,durationMs:1750});expect(JSON.stringify(value)).not.toContain('Private')
 const draft=courseGapPlacementDraft(p,value,'en');expect(draft).toEqual({lessonId:'lesson',demoId:'',offset:'1.25',duration:'1.75',sourceOffset:'0'})
 const request={lessonId:draft.lessonId,demoId:draft.demoId,lessonOffsetMs:parseDemoSeconds(draft.offset),sourceOffsetMs:0,durationMs:parseDemoSeconds(draft.duration)}
 expect(()=>reviewCourseDemoPlacement(p,request)).toThrow('time');const reviewed=reviewCourseDemoPlacement(p,{...request,demoId:'demo'}),snapshot=vi.fn(),persist=vi.fn();expect(()=>commitCourseDemoPlacement(p,reviewed,false,{snapshot,persist})).toThrow('ack');expect(persist).not.toHaveBeenCalled()
 const next=commitCourseDemoPlacement(p,reviewed,true,{snapshot,persist});expect(next.tracks.at(-1)?.clips[0]).toMatchObject({startMs:3250,durationMs:1750,gain:0,speed:1});expect(courseProductionOverview(next)[0].visuals.gaps).toEqual([]);expect(next.assets).toEqual(p.assets);expect(next.metadata).toEqual(p.metadata);expect(snapshot).toHaveBeenCalledTimes(1);expect(JSON.stringify(p)).toBe(before)
})
it.each([{startMs:1251,endMs:3000},{startMs:1250,endMs:2999},{startMs:-1,endMs:3000},{startMs:NaN,endMs:3000},{startMs:3000,endMs:1250}])('rejects a guessed or partial interval %j',value=>expect(()=>prepareCourseGapPlacement(fixture(),'lesson',value,'en')).toThrow())
it('rejects missing lessons and genuine sub-250ms gaps, accepts exact 250ms',()=>{const p=fixture();expect(()=>prepareCourseGapPlacement(p,'missing',gap,'en')).toThrow();p.tracks[0].clips[0].durationMs=2751;expect(()=>prepareCourseGapPlacement(p,'lesson',{startMs:2751,endMs:3000},'en')).toThrow();p.tracks[0].clips[0].durationMs=2750;expect(prepareCourseGapPlacement(p,'lesson',{startMs:2750,endMs:3000},'en').durationMs).toBe(250)})
it.each(['offline','missing','muted'] as const)('protects existing %s visuals without inventing usable gaps',issue=>{const p=fixture();if(issue==='offline')p.assets[0].offline=true;if(issue==='missing')p.assets=[];if(issue==='muted')p.tracks[0].muted=true;const actual=courseProductionOverview(p)[0].visuals.gaps[0];expect(actual).toEqual({startMs:0,endMs:3000});if(issue==='muted')expect(prepareCourseGapPlacement(p,'lesson',actual,'en').durationMs).toBe(3000);else expect(()=>prepareCourseGapPlacement(p,'lesson',actual,'en')).toThrow('Existing visual')})
it.each(['project','language','dirty'] as const)('permanently invalidates observed %s A–B–A',change=>{const p=fixture(),value=prepareCourseGapPlacement(p,'lesson',gap,'en');expect(courseGapPlacementIsCurrent(change==='project'?{...p,title:'Other'}:p,value,change==='language'?'fr':'en',change==='dirty')).toBe(false);expect(courseGapPlacementIsCurrent(p,value,'en')).toBe(false);expect(()=>courseGapPlacementDraft(p,value,'en')).toThrow('no longer current')})
it('rejects serialized/forged selections and never trims a short source to fit',()=>{const p=fixture(),v=prepareCourseGapPlacement(p,'lesson',gap,'en');expect(courseGapPlacementIsCurrent(p,{...v},'en')).toBe(false);expect(()=>courseGapPlacementDraft(p,JSON.parse(JSON.stringify(v)),'en')).toThrow();p.assets[0].kind='video';p.assets[0].metadata.durationMs=1000;const course=p.metadata.courseOutline as any;course.modules[0].lessons[0].demonstrations[0].evidence.kind='video';const req={lessonId:'lesson',demoId:'demo',lessonOffsetMs:1250,durationMs:1750,sourceOffsetMs:0};expect(()=>reviewCourseDemoPlacement(p,req)).toThrow('overrun')})
it.each(['de','en','fr'] as const)('renders %s explicit draft replacement with no automatic activity',language=>{const p=fixture(),pendingGap=prepareCourseGapPlacement(p,'lesson',gap,language),persist=vi.fn(),fetch=vi.spyOn(globalThis,'fetch'),history=new PersistentVersionHistory({getItem:()=>null,setItem:persist,removeItem:persist});try{
 const html=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:language,children:createElement(CourseDemoPlacementPanel,{project:p,dirty:false,history,onProjectChange:persist,pendingGap,onClearGap:persist})}));expect(html).toContain(translateUi(language,'course.gap.replace'));expect(html).toContain(translateUi(language,'course.gap.keep'));expect(html).toContain('Original lesson');expect(html).not.toContain('Private script');expect(html).toContain('value="5"');expect(html).toContain('value="0"')
 const overview=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:language,children:createElement(CourseProductionOverviewPanel,{project:p,dirty:true,onEditLesson:persist,onPrepareGap:persist})}));expect(overview).toContain(translateUi(language,'course.gap.help'));expect(overview).toContain('disabled=""');expect(persist).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled()
 }finally{fetch.mockRestore()}})
