import {it,expect,vi} from 'vitest'
import {createElement} from 'react'
import {renderToStaticMarkup} from 'react-dom/server'
import {createProject,parseProject} from '../src/core/project'
import {newCourseOutline,saveCourseOutline} from '../src/core/course'
import {courseProductionOverview,filterCourseOverview} from '../src/core/courseProductionOverview'
import {createCourseProductionHandoff,resolveCourseProductionHandoff} from '../src/core/courseProductionHandoff'
import {CourseProductionOverviewPanel} from '../src/components/CourseProductionOverviewPanel'
import {UiLanguageProvider} from '../src/components/UiLanguageProvider'
import {translateUi} from '../src/core/uiMessages'
function fixture(){const p=parseProject({...createProject('Overview actions'),assets:[{id:'audio',kind:'audio',managed:true,uri:'KINAOU/Assets/voice.wav',metadata:{durationMs:4000}}],tracks:[{id:'voice',type:'voice',name:'Voice',clips:[{id:'v',assetId:'audio',startMs:0,durationMs:2000,sourceOffsetMs:0,gain:1,speed:1}]}]});return saveCourseOutline(p,{...newCourseOutline(p),language:'fr',modules:[{id:'module',title:'Module',lessons:[{id:'one',title:'Première',script:'PRIVATE_SCRIPT',objective:'',range:{inMs:0,outMs:1000}},{id:'two',title:'Deuxième',script:'',objective:'',range:{inMs:1000,outMs:2000}},{id:'three',title:'Troisième',script:'Later script',objective:'',range:{inMs:2000,outMs:3000}}]}]})}
it.each(['de','en','fr'] as const)('renders %s independent per-lesson eligibility and original titles without opening or exposing scripts',language=>{
 const p=fixture(),open=vi.fn(),fetch=vi.spyOn(globalThis,'fetch');try{const html=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:language,children:createElement(CourseProductionOverviewPanel,{project:p,dirty:false,onEditLesson:open,onOpenProduction:open})})),articles=html.match(/<article[\s\S]*?<\/article>/g)!
 expect(articles).toHaveLength(3);for(const article of articles){expect(article).toContain(translateUi(language,'course.handoff.narration'));expect(article).toContain(translateUi(language,'course.handoff.export'))}
 expect(articles[0].match(/disabled=""/g)??[]).toHaveLength(0);expect(articles[1].match(/disabled=""/g)).toHaveLength(1);expect(articles[1]).toContain(translateUi(language,'course.handoff.noScript'));expect(articles[2].match(/disabled=""/g)).toHaveLength(1);expect(articles[2]).toContain(translateUi(language,'course.handoff.invalidRange'));expect(html).toContain('Troisième');expect(html).not.toContain('PRIVATE_SCRIPT');expect(open).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled()
 }finally{fetch.mockRestore()}
})
it('blocks all direct actions for a dirty outline and exposes none without a recipient',()=>{const props={project:fixture(),dirty:true,onEditLesson:vi.fn()},html=renderToStaticMarkup(createElement(CourseProductionOverviewPanel,{...props,onOpenProduction:vi.fn()}));expect(html.match(/button disabled=""/g)).toHaveLength(9);expect(renderToStaticMarkup(createElement(CourseProductionOverviewPanel,props))).not.toContain('Open lesson in Audio Studio')})
it('filters exact voice gaps independently of scripts, visual gaps or zero-gain music',()=>{const p=fixture(),rows=courseProductionOverview(p);expect(filterCourseOverview(rows,'voiceGaps').map(r=>r.lessonId)).toEqual(['three']);expect(filterCourseOverview(rows,'noScript').map(r=>r.lessonId)).toEqual(['two']);expect(filterCourseOverview(rows,'visualGaps')).toHaveLength(3);p.tracks[0].muted=true;expect(filterCourseOverview(courseProductionOverview(p),'voiceGaps')).toHaveLength(3)})
it('keeps selected stable lesson identity through filtering and requires existing guarded recipient resolution',()=>{const p=fixture(),row=filterCourseOverview(courseProductionOverview(p),'voiceGaps')[0],handoff=createCourseProductionHandoff(p,row.lessonId,'narration');expect(resolveCourseProductionHandoff(p,handoff,'narration')).toMatchObject({id:'three',script:'Later script'});expect(()=>createCourseProductionHandoff(p,row.lessonId,'export')).toThrow();expect(()=>resolveCourseProductionHandoff({...p,title:'Changed'},handoff,'narration')).toThrow();expect(()=>resolveCourseProductionHandoff(p,handoff,'narration')).toThrow()})
