import {it,expect,vi} from 'vitest'
import {readFileSync} from 'node:fs'
import {createElement} from 'react'
import {renderToStaticMarkup} from 'react-dom/server'
import {createProject,parseProject} from '../src/core/project'
import {buildFrameProvenance,hasFrameProvenance} from '../src/core/frameProvenance'
import {SourceProvenanceSession} from '../src/core/sourceProvenance'
import {ProjectAssetList} from '../src/components/ProjectAssetList'
import {UiLanguageProvider} from '../src/components/UiLanguageProvider'
import {PersistentVersionHistory} from '../src/core/versioning'
import {translateUi} from '../src/core/uiMessages'
const date='2026-10-03T21:18:25.975Z',annotations=JSON.parse(readFileSync('tests/fixtures/annotated-source-frame.json','utf8'))
function fixture(){const source={id:'source',kind:'video',uri:'KINAOU/Assets/red-blue.mp4',managed:true,offline:false,metadata:{name:'Synthetic source',synthetic:true,sizeBytes:22889,durationMs:2000}},extraction={schemaVersion:1,sourcePath:source.uri,requestedMs:1200,sourceDurationMs:2000,sourceSizeBytes:22889,sourceWidth:160,sourceHeight:90,width:160,height:90,sizeBytes:311,sha256:annotations.sourcePngSha256,extractedAt:date};return parseProject({...createProject('Frame report'),script:'UNRELATED_SECRET',assets:[source,{id:'frame',kind:'image',uri:'KINAOU/Assets/annotated.png',managed:true,metadata:{name:'Authored <keep>',sourceKind:'annotated-video-frame-v1',extractionOnly:false,modified:true,sourceHashVerified:false,timing:'requested-time-frame-quantized',sourceAsset:source,extraction,annotations:structuredClone(annotations),mimeType:'image/png',sizeBytes:2253}}],tracks:[{id:'a',name:'Active',type:'image',clips:[{id:'shown',assetId:'frame',startMs:5000,durationMs:3000}]},{id:'b',name:'Muted',type:'broll',muted:true,clips:[{id:'hidden',assetId:'frame',startMs:0,durationMs:1000}]}]})}
it('reports retained actual annotation record and timeline uses without fresh integrity or visibility claims',()=>{const project=fixture(),before=JSON.stringify(project),review=buildFrameProvenance(project,'frame','en',new Date(date)),report=JSON.parse(review.files.json.text);expect(report).toMatchObject({modified:true,currentSourceState:'same-record',currentFileHashReverified:false,sourceFileHashReverified:false,finishedExportInspected:false,legalClearance:false,sourceAsset:{metadata:{synthetic:true}},annotations,extraction:{requestedMs:1200,sizeBytes:311},outputPngSha256:annotations.outputPngSha256});expect(report.timelineUses).toMatchObject([{startMs:5000,endMs:8000,trackMuted:false},{startMs:0,endMs:1000,trackMuted:true}]);expect(review.files.text.text).toContain('Press');expect(review.files.text.text).toContain('Synthetic source');expect(review.files.json.text).not.toContain('UNRELATED_SECRET');expect(JSON.stringify(project)).toBe(before);report.sourceAsset.metadata.synthetic=false;expect(project.assets[0].metadata.synthetic).toBe(true)})
it.each(['changed-record','missing'] as const)('keeps historical source when current source is %s',state=>{const project=fixture();if(state==='missing')project.assets.shift();else project.assets[0].metadata.name='Changed';const report=JSON.parse(buildFrameProvenance(project,'frame','fr').files.json.text);expect(report.currentSourceState).toBe(state);expect(report.sourceAsset.metadata.name).toBe('Synthetic source')})
it('accepts an unannotated historical frame and does not infer that synthetic source is authentic',()=>{const project=fixture(),metadata=project.assets[1].metadata;metadata.sourceKind='extracted-video-frame-v1';metadata.extractionOnly=true;delete metadata.modified;delete metadata.annotations;metadata.sizeBytes=311;const report=JSON.parse(buildFrameProvenance(project,'frame','de').files.json.text);expect(report.modified).toBe(false);expect(report.annotations).toBe(null);expect(report.outputPngSha256).toBe(annotations.sourcePngSha256);expect(report.sourceAsset.metadata.synthetic).toBe(true)})
it.each(['kind','unmanaged','path','duplicate','sourceDuplicate','binding','sameId','duration','sourceSize','time','dimensions','hash','marks','flag','missingMarks','originalMarks','originalSize','mime','huge','provenance'] as const)('refuses corrupt/contradictory frame provenance %s',fault=>{const p=fixture(),a=p.assets[1],m=a.metadata as any;if(fault==='kind')a.kind='video';if(fault==='unmanaged')a.managed=false;if(fault==='path')a.uri='KINAOU/Assets/../secret.png';if(fault==='duplicate')p.assets.push(structuredClone(a));if(fault==='sourceDuplicate')p.assets.push(structuredClone(p.assets[0]));if(fault==='binding')m.sourceAsset.uri='KINAOU/Assets/other.mp4';if(fault==='sameId')m.sourceAsset.id=a.id;if(fault==='duration')m.sourceAsset.metadata.durationMs=9000;if(fault==='sourceSize')m.extraction.sourceSizeBytes=2**32;if(fault==='time')m.extraction.requestedMs=2000;if(fault==='dimensions'){m.extraction.sourceWidth=7680;m.extraction.sourceHeight=7680}if(fault==='hash')m.annotations.sourcePngSha256='a'.repeat(64);if(fault==='marks')m.annotations.marks=[];if(fault==='flag')m.modified=false;if(fault==='missingMarks')delete m.annotations;if(fault==='originalMarks'){m.sourceKind='extracted-video-frame-v1';m.extractionOnly=true;m.modified=false}if(fault==='originalSize'){m.sourceKind='extracted-video-frame-v1';m.extractionOnly=true;delete m.modified;delete m.annotations}if(fault==='mime')m.mimeType='image/jpeg';if(fault==='huge')m.sourceAsset.metadata.extra='x'.repeat(48001);if(fault==='provenance')m.sourceAsset.metadata.sourceImport={schemaVersion:5};expect(()=>buildFrameProvenance(p,'frame','en')).toThrow()})
it.each(['project','asset','language'] as const)('invalidates observed %s A/B/A report acknowledgement',fault=>{const p=fixture(),s=new SourceProvenanceSession(),r=s.prepare(p,'frame','en',new Date(date),buildFrameProvenance);s.observe(fault==='project'?{...p,title:'B'}:p,fault==='asset'?'source':'frame',fault==='language'?'de':'en');s.observe(p,'frame','en');expect(s.current(r)).toBe(false);expect(()=>s.download(r,'json',true)).toThrow()})
it('downloads exact acknowledged bytes only, refuses tampering, and does not retain unrelated data',()=>{const p=fixture(),s=new SourceProvenanceSession(),r=s.prepare(p,'frame','en',new Date(date),buildFrameProvenance);expect(()=>s.download(r,'text',false)).toThrow();expect(s.download(r,'text',true)).toEqual(r.files.text);expect(()=>s.download(structuredClone(r),'json',true)).toThrow();r.files.text.text+='tampered';expect(()=>s.download(r,'text',true)).toThrow()})
it.each(['de','en','fr'] as const)('shows explicit-only %s frame report in actual asset library without requests or writes',language=>{const project=fixture(),before=JSON.stringify(project),fetch=vi.spyOn(globalThis,'fetch'),write=vi.fn(),history=new PersistentVersionHistory({getItem:()=>null,setItem:()=>{},removeItem:()=>{}});try{const html=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:language,children:createElement(ProjectAssetList,{project,history,workerUrl:'http://127.0.0.1:44018',workerToken:'',workerConnected:false,workerCapabilities:[],onProjectChange:write})}));expect(html).toContain(translateUi(language,'frameReport.heading'));expect(html).not.toContain(annotations.outputPngSha256);expect(fetch).not.toHaveBeenCalled();expect(write).not.toHaveBeenCalled();expect(JSON.stringify(project)).toBe(before)}finally{fetch.mockRestore()}})
it('finds corrupt records for explicit refusal but does not invent provenance for legacy images',()=>{const p=fixture();expect(hasFrameProvenance(p.assets[1])).toBe(true);p.assets[1].metadata={extraction:null};expect(hasFrameProvenance(p.assets[1])).toBe(true);expect(()=>buildFrameProvenance(p,'frame','en')).toThrow();p.assets[1].metadata={};expect(hasFrameProvenance(p.assets[1])).toBe(false);expect(hasFrameProvenance(undefined)).toBe(false)})
