import{it,expect,vi}from'vitest'
import{readFileSync}from'node:fs'
import{createElement}from'react'
import{renderToStaticMarkup}from'react-dom/server'
import{createProject,parseProject}from'../src/core/project'
import{prepareFrameRevision,matchFrameRevision}from'../src/core/frameRevision'
import{buildFrameProvenance}from'../src/core/frameProvenance'
import{parseSourceFrameResult}from'../src/core/sourceFrame'
import{FrameRevisionControl}from'../src/components/FrameRevisionControl'
import{FrameAnnotationEditor}from'../src/components/FrameAnnotationEditor'
import{UiLanguageProvider}from'../src/components/UiLanguageProvider'
import{PersistentVersionHistory}from'../src/core/versioning'
import{translateUi}from'../src/core/uiMessages'
const annotations=JSON.parse(readFileSync('tests/fixtures/annotated-source-frame.json','utf8'))
function fixture(){const source={id:'source',kind:'video',uri:'KINAOU/Assets/red-blue.mp4',managed:true,offline:false,metadata:{sizeBytes:22889,durationMs:2000,synthetic:true}},extraction={schemaVersion:1,sourcePath:source.uri,requestedMs:1200,sourceDurationMs:2000,sourceSizeBytes:22889,sourceWidth:160,sourceHeight:90,width:160,height:90,sizeBytes:311,sha256:annotations.sourcePngSha256,extractedAt:'2026-10-03T21:18:25.975Z'};return parseProject({...createProject('New version'),assets:[source,{id:'parent',kind:'image',uri:'KINAOU/Assets/annotated.png',managed:true,metadata:{sourceKind:'annotated-video-frame-v1',extractionOnly:false,modified:true,sourceHashVerified:false,timing:'requested-time-frame-quantized',sourceAsset:source,extraction,annotations:structuredClone(annotations),mimeType:'image/png',sizeBytes:2253}}]})}
async function extracted(project=fixture()){const seed=prepareFrameRevision(project,'parent');return parseSourceFrameResult({...seed.expected,pngBase64:readFileSync('tests/fixtures/annotation-base-frame.png').toString('base64'),extractedAt:'2026-10-04T00:00:00.000Z'},{path:seed.expected.sourcePath,timeMs:seed.expected.requestedMs})}
it('loads a private editing template only from bound available original source and verifies real base PNG bytes',async()=>{const p=fixture(),before=JSON.stringify(p),seed=prepareFrameRevision(p,'parent'),frame=await extracted(p);expect(seed.marks).toEqual(annotations.marks);expect(matchFrameRevision(seed,frame)).toEqual({parentAssetId:'parent',parentPngSha256:annotations.outputPngSha256});seed.marks[0].x1=99;seed.expected.sha256='a'.repeat(64);expect(JSON.stringify(p)).toBe(before)})
it.each(['missing','offline','unmanaged','changed','duplicate','corrupt','sameParent'] as const)('refuses unavailable/changed revision source %s before any request',fault=>{const p=fixture();if(fault==='missing')p.assets.shift();if(fault==='offline')p.assets[0].offline=true;if(fault==='unmanaged')p.assets[0].managed=false;if(fault==='changed')p.assets[0].metadata.name='new';if(fault==='duplicate')p.assets.push(structuredClone(p.assets[0]));if(fault==='corrupt')p.assets[1].metadata.annotations={};if(fault==='sameParent')p.assets[1].metadata.frameRevision={parentAssetId:'parent',parentPngSha256:annotations.outputPngSha256};const fetch=vi.spyOn(globalThis,'fetch');try{expect(()=>prepareFrameRevision(p,'parent')).toThrow();expect(fetch).not.toHaveBeenCalled()}finally{fetch.mockRestore()}})
it.each(['sourcePath','requestedMs','sourceDurationMs','sourceSizeBytes','sourceWidth','sourceHeight','width','height','sizeBytes','sha256'] as const)('refuses changed extracted %s instead of attaching old marks to a different frame',async key=>{const p=fixture(),seed=prepareFrameRevision(p,'parent'),frame=await extracted(p);Object.assign(frame.record,{[key]:typeof frame.record[key]==='number'?Number(frame.record[key])+1:'changed'});expect(()=>matchFrameRevision(seed,frame)).toThrow(/no longer matches/)})
it('unmarked source frames can start a new editable version without inventing earlier marks',()=>{const p=fixture(),m=p.assets[1].metadata;m.sourceKind='extracted-video-frame-v1';m.extractionOnly=true;delete m.modified;delete m.annotations;m.sizeBytes=311;const seed=prepareFrameRevision(p,'parent');expect(seed.marks).toEqual([]);expect(seed.parentPngSha256).toBe(annotations.sourcePngSha256)})
it('retains explicit previous-version lineage in both historical reports without requiring the old file',()=>{const p=fixture(),child=structuredClone(p.assets[1]);child.id='new';child.uri='KINAOU/Assets/revision.png';child.metadata.frameRevision={parentAssetId:'parent',parentPngSha256:annotations.outputPngSha256};p.assets.push(child);p.assets.splice(1,1);const report=buildFrameProvenance(p,'new','en');expect(JSON.parse(report.files.json.text).frameRevision).toEqual(child.metadata.frameRevision);expect(report.files.text.text).toContain('Previous image version');expect(report.files.text.text).toContain('parent')})
it.each(['de','en','fr'] as const)('exposes explicit-only %s reopening with no extraction/import/project writes',language=>{const p=fixture(),persist=vi.fn(),fetch=vi.spyOn(globalThis,'fetch'),history=new PersistentVersionHistory({getItem:()=>null,setItem:()=>{},removeItem:()=>{}});try{const html=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:language,children:createElement(FrameRevisionControl,{project:p,asset:p.assets[1],history,workerUrl:'http://127.0.0.1:44018',workerToken:'',workerConnected:false,workerCapabilities:[],onProjectChange:persist})}));expect(html).toContain(translateUi(language,'frameRevision.heading'));expect(html).toContain(translateUi(language,'frameRevision.open'));expect(html).not.toContain('<canvas');expect(fetch).not.toHaveBeenCalled();expect(persist).not.toHaveBeenCalled()}finally{fetch.mockRestore()}})
it('initial editor retains saved labels and coordinates without calling review/save',async()=>{const p=fixture(),seed=prepareFrameRevision(p,'parent'),onChange=vi.fn(),onReviewed=vi.fn(),html=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:'en',children:createElement(FrameAnnotationEditor,{frame:await extracted(p),initialMarks:seed.marks,disabled:false,onChange,onReviewed})}));expect(html).toContain('Press');expect(html).toContain('value="21"');expect(onChange).not.toHaveBeenCalled();expect(onReviewed).not.toHaveBeenCalled()})
