import {afterEach,it,expect,vi} from 'vitest'
import {frameAnnotationsSchema,newFrameMark,frameAnnotationPoint,paintFrameAnnotations,loadFrameBitmap,framePngHash,rasterizeFrameAnnotations,type SourceFrame} from '../src/core/frameAnnotations'
import {createElement} from 'react'
import {renderToStaticMarkup} from 'react-dom/server'
import {FrameAnnotationEditor} from '../src/components/FrameAnnotationEditor'
import {UiLanguageProvider} from '../src/components/UiLanguageProvider'
import {translateUi} from '../src/core/uiMessages'
afterEach(()=>{vi.unstubAllGlobals();vi.useRealTimers()})
function context(){return {save:vi.fn(),restore:vi.fn(),strokeRect:vi.fn(),beginPath:vi.fn(),moveTo:vi.fn(),lineTo:vi.fn(),stroke:vi.fn(),closePath:vi.fn(),fill:vi.fn(),fillRect:vi.fn(),fillText:vi.fn(),measureText:vi.fn(()=>({width:30})),drawImage:vi.fn()} as unknown as CanvasRenderingContext2D}
async function frame(){const file=new File([new Uint8Array(50)],'source.png',{type:'image/png'});return {file,record:{width:160,height:90,sizeBytes:50,sha256:await framePngHash(await file.arrayBuffer())}} as SourceFrame}
it.each(['duplicate','count','empty','short','thin','bounds','nan','control','surrogate','extra'] as const)('refuses invalid annotation %s',fault=>{const a=newFrameMark('arrow'),marks=[a];if(fault==='duplicate')marks.push({...a});if(fault==='count')marks.push(...Array.from({length:16},()=>newFrameMark('box')));if(fault==='empty'){a.kind='label';a.text='  '}if(fault==='short'){a.x2=a.x1;a.y2=a.y1}if(fault==='thin'){a.kind='box';a.x2=a.x1}if(fault==='bounds')a.x1=101;if(fault==='nan')a.y2=NaN;if(fault==='control')a.text='a\n';if(fault==='surrogate')a.text='\ud800';if(fault==='extra')Object.assign(a,{url:'https://example.org'});expect(()=>frameAnnotationsSchema.parse(marks)).toThrow()})
it('normalizes click coordinates, clamps outside points and refuses unusable geometry',()=>{expect(frameAnnotationPoint(60,45,{left:10,top:20,width:100,height:50})).toEqual({x:50,y:50});expect(frameAnnotationPoint(-10,999,{left:0,top:0,width:100,height:100})).toEqual({x:0,y:100});expect(()=>frameAnnotationPoint(0,0,{left:0,top:0,width:0,height:10})).toThrow()})
it('paints real arrow, reversed box and inset label without changing its retained coordinates',()=>{const c=context(),arrow=newFrameMark('arrow'),box={...newFrameMark('box'),x1:90,y1:90,x2:10,y2:10},label={...newFrameMark('label','Press'),x1:100,y1:100},marks=[arrow,box,label],before=JSON.stringify(marks);paintFrameAnnotations(c,160,90,marks);expect(c.strokeRect).toHaveBeenCalledWith(16,9,128,72);expect(c.fill).toHaveBeenCalledOnce();expect(c.fillText).toHaveBeenCalledWith('Press',126,72);expect(c.restore).toHaveBeenCalledTimes(3);expect(JSON.stringify(marks)).toBe(before)})
it('refuses labels that cannot fit and restores context even on refusal',()=>{const c=context();vi.mocked(c.measureText).mockReturnValue({width:999} as TextMetrics);expect(()=>paintFrameAnnotations(c,160,90,[newFrameMark('label','Too long')])).toThrow(/fit/);expect(c.restore).toHaveBeenCalledOnce();expect(()=>paintFrameAnnotations(c,1921,1080,[])).toThrow()})
it('checks original hash before decoding and closes a mismatched bitmap',async()=>{const f=await frame(),close=vi.fn(),decode=vi.fn(async()=>({width:161,height:90,close}));vi.stubGlobal('createImageBitmap',decode);await expect(loadFrameBitmap(f)).rejects.toThrow(/dimensions/);expect(close).toHaveBeenCalledOnce();f.record.sha256='0'.repeat(64);await expect(loadFrameBitmap(f)).rejects.toThrow(/differs/);expect(decode).toHaveBeenCalledOnce()})
it('closes a late decoded bitmap after timeout',async()=>{vi.useFakeTimers();const f=await frame(),close=vi.fn();let resolve!:(value:unknown)=>void;vi.stubGlobal('createImageBitmap',vi.fn(()=>new Promise(r=>{resolve=r})));const result=loadFrameBitmap(f);const rejected=expect(result).rejects.toThrow(/timed out/);await vi.waitFor(()=>expect(resolve).toBeTypeOf('function'));await vi.advanceTimersByTimeAsync(15000);await rejected;resolve({width:160,height:90,close});await Promise.resolve();expect(close).toHaveBeenCalledOnce()})
it('encodes reviewed bytes with both hashes and privately retained annotations, without fetching or mutating original',async()=>{const f=await frame(),before=await f.file.arrayBuffer(),close=vi.fn(),ctx=context(),blob=new Blob([new Uint8Array(60).fill(7)],{type:'image/png'});vi.stubGlobal('createImageBitmap',async()=>({width:160,height:90,close}));vi.stubGlobal('document',{createElement:()=>({getContext:()=>ctx,toBlob:(done:(value:Blob)=>void)=>done(blob)})});const fetch=vi.fn();vi.stubGlobal('fetch',fetch);const marks=[newFrameMark('arrow')],result=await rasterizeFrameAnnotations(f,marks);marks[0].x1=99;expect(result.provenance.marks[0].x1).toBe(20);expect(result.file.size).toBe(60);expect(result.provenance).toMatchObject({sourcePngSha256:f.record.sha256,outputPngSha256:await framePngHash(await blob.arrayBuffer()),renderer:'canvas-source-annotations-v1'});expect(await f.file.arrayBuffer()).toEqual(before);expect(ctx.drawImage).toHaveBeenCalledOnce();expect(close).toHaveBeenCalledOnce();expect(fetch).not.toHaveBeenCalled()})
it.each(['null','throw','type'] as const)('fails closed on PNG encoder %s and closes bitmap',async fault=>{const f=await frame(),close=vi.fn();vi.stubGlobal('createImageBitmap',async()=>({width:160,height:90,close}));vi.stubGlobal('document',{createElement:()=>({getContext:()=>context(),toBlob:(done:(value:Blob|null)=>void)=>{if(fault==='throw')throw Error('encoder failed');done(fault==='null'?null:new Blob([new Uint8Array(60)],{type:'image/jpeg'}))}})});await expect(rasterizeFrameAnnotations(f,[newFrameMark('arrow')])).rejects.toThrow();expect(close).toHaveBeenCalledOnce()})
it.each(['de','en','fr'] as const)('renders localized %s editor with disabled export and no side effects',async language=>{const f=await frame(),onReviewed=vi.fn(),onChange=vi.fn(),html=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:language,children:createElement(FrameAnnotationEditor,{frame:f,disabled:false,onReviewed,onChange})}));expect(html).toContain(translateUi(language,'frameMarks.heading'));expect(html).toContain(translateUi(language,'frameMarks.add.arrow'));expect(html).toContain('disabled=""');expect(onReviewed).not.toHaveBeenCalled();expect(onChange).not.toHaveBeenCalled()})
