import {it,expect,vi} from 'vitest'
import {createElement} from 'react'
import {renderToStaticMarkup} from 'react-dom/server'
import {createProject} from '../src/core/project'
import {SourceImportRegistration,retainSourceImportReminder,readSourceImportReminder,forgetSourceImportReminder} from '../src/core/sourceImport'
import {sourceImportRequestSchema,sourceImportPath,validateSourceImportJob,type SourceImportJob} from '../worker/source-import-protocol.mjs'
import {WorkerClient} from '../src/core/workerClient'
import {SourceImportPanel} from '../src/components/SourceImportPanel'
import {UiLanguageProvider} from '../src/components/UiLanguageProvider'
import {translateUi} from '../src/core/uiMessages'
import {PersistentVersionHistory} from '../src/core/versioning'
const id='8f630526-e4dc-434c-a898-a11a310f4567',date='2026-10-03T00:00:00.000Z',url='https://media.example.org/source.mp4'
function fixture(){const project=createProject('Authorized source'),request=sourceImportRequestSchema.parse({id,projectId:project.id,name:'Own demonstration',downloadUrl:url,sourcePageUrl:'https://media.example.org/source',creator:'Creator',permissionBasis:'permission',evidence:'Written permission for direct download and stated reuse',attribution:'Creator / source',intendedUse:'Private tactical demonstration, no publication in this test',acquisitionConfirmed:true,reuseConfirmed:true,reviewedAt:date}),managedPath=sourceImportPath(id),job:SourceImportJob={request,state:'succeeded',createdAt:date,updatedAt:date,receivedBytes:16,result:{managedPath,sizeBytes:16,sha256:'a'.repeat(64),requestedUrl:url,finalUrl:url,redirectUrls:[],retrievedAt:date,mimeType:'video/mp4',legalClearance:false,probe:{path:managedPath,sizeBytes:16,durationMs:1000,width:160,height:90,videoCodec:'h264',fps:30}}};return{project,request,job}}
it('registers exactly one source with complete provenance, actual measurements and no timeline placement',()=>{const{project,job}=fixture(),before=JSON.stringify(project),save=vi.fn(),snapshot=vi.fn(),review=new SourceImportRegistration(project,job),next=review.commit(project,snapshot,save);expect(next.assets).toHaveLength(1);expect(next.tracks).toEqual(project.tracks);expect(next.assets[0].metadata).toMatchObject({width:160,height:90,durationMs:1000,sourceImport:{request:job.request,result:job.result}});expect(JSON.stringify(project)).toBe(before);expect(snapshot).toHaveBeenCalledOnce();expect(()=>review.commit(project,snapshot,save)).toThrow();expect(()=>new SourceImportRegistration(next,job)).toThrow(/already/)} )
it('save-only retries use identical prepared bytes and one successful safety snapshot despite callback mutation',()=>{const{project,job}=fixture(),review=new SourceImportRegistration(project,job),attempts:string[]=[],snapshot=vi.fn();let fail=true
 const persist=(value:typeof project)=>{attempts.push(JSON.stringify(value));value.assets=[];if(fail)throw Error('disk full')}
 expect(()=>review.commit(project,snapshot,persist)).toThrow();fail=false;const next=review.commit(project,snapshot,persist);expect(attempts[0]).toBe(attempts[1]);expect(snapshot).toHaveBeenCalledOnce();expect(next.assets).toHaveLength(1)
})
it('failed/false safety and persistence acknowledgements never report completion',()=>{const{project,job}=fixture(),review=new SourceImportRegistration(project,job),persist=vi.fn();expect(()=>review.commit(project,()=>false,persist)).toThrow();expect(persist).not.toHaveBeenCalled();expect(()=>review.commit(project,()=>{},()=>false)).toThrow();expect(review.commit(project,()=>{throw Error('must not repeat')},persist).assets).toHaveLength(1)})
it('observed project A/B/A permanently retires a registration',()=>{const{project,job}=fixture(),review=new SourceImportRegistration(project,job);review.observe({...project,title:'B'});review.observe(project);expect(()=>review.commit(project,vi.fn(),vi.fn())).toThrow(/stale/)})
it.each(['other-project','unfinished','hash','path','redirect','measurement','confirmed'])('rejects %s source acknowledgement',kind=>{const{project,job}=fixture(),bad=structuredClone(job);if(kind==='other-project')bad.request.projectId='other';if(kind==='unfinished')bad.state='downloading';if(kind==='hash')bad.result!.sha256='bad';if(kind==='path')bad.result!.managedPath='KINAOU/Assets/other.mp4';if(kind==='redirect')bad.result!.finalUrl='https://other.example.org/a.mp4';if(kind==='measurement')bad.result!.probe.sizeBytes=32;if(kind==='confirmed')(bad.request as any).reuseConfirmed=false;expect(()=>new SourceImportRegistration(project,bad)).toThrow()})
function storage(){const values=new Map<string,string>();return{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)},removeItem:(key:string)=>{values.delete(key)}}}
it('writes/readbacks a credential-free reminder, refuses overwrite, reloads and explicitly forgets it',()=>{const{request,project}=fixture(),store=storage(),ticket={schemaVersion:1 as const,workerUrl:'http://127.0.0.1:43996',request};expect(readSourceImportReminder(store,project.id)).toBeNull();expect(retainSourceImportReminder(store,ticket)).toEqual(ticket);expect(readSourceImportReminder(store,project.id)).toEqual(ticket);expect(JSON.stringify(ticket)).not.toContain('token');expect(()=>retainSourceImportReminder(store,ticket)).toThrow();forgetSourceImportReminder(store,project.id);expect(readSourceImportReminder(store,project.id)).toBeNull()})
it('refuses failed storage readback before a caller can submit a download',()=>{const{request}=fixture();expect(()=>retainSourceImportReminder({getItem:()=>null,setItem:()=>{},removeItem:()=>{}},{schemaVersion:1,workerUrl:'http://127.0.0.1:43996',request})).toThrow(/read back/)})
it.each(['https://example.com','http://u:p@localhost:1','http://localhost:1/path','http://localhost:1?token=x'])('refuses reminder worker URL %s',workerUrl=>{const{request}=fixture();expect(()=>retainSourceImportReminder(storage(),{schemaVersion:1,workerUrl,request})).toThrow()})
it('client submits validated reviewed input once and status/cancel only retain the exact ID',async()=>{const{request,job}=fixture(),fetchImpl=vi.fn(async(_input:RequestInfo|URL,_init?:RequestInit)=>Response.json({ok:true,type:'source-import',job})),client=new WorkerClient({baseUrl:'http://127.0.0.1:43996',token:'PRIVATE',fetchImpl});expect(await client.startSourceImport(request)).toEqual(validateSourceImportJob(job,request));await client.sourceImportStatus(request);await client.sourceImportStatus(request,true);expect(fetchImpl.mock.calls.map(c=>c[0])).toEqual(['http://127.0.0.1:43996/source-import/start','http://127.0.0.1:43996/source-import/status','http://127.0.0.1:43996/source-import/cancel']);expect(fetchImpl.mock.calls[1][1]).toMatchObject({body:JSON.stringify({id}),redirect:'error',headers:{authorization:'Bearer PRIVATE'}})})
it.each(['de','en','fr'] as const)('renders closed explicit-only %s import without requests or project writes',language=>{const{project}=fixture(),write=vi.fn(),fetch=vi.spyOn(globalThis,'fetch'),history=new PersistentVersionHistory(storage());try{const html=renderToStaticMarkup(createElement(UiLanguageProvider,{initialLanguage:language,children:createElement(SourceImportPanel,{project,history,workerUrl:'http://127.0.0.1:43996',workerToken:'test',workerConnected:true,workerCapabilities:['source-import'],onProjectChange:write})}));expect(html).toContain(translateUi(language,'sourceImport.heading'));expect(html).toContain(translateUi(language,'sourceImport.help'));expect(html).toContain('<details class="card sourceImportPanel">');expect(fetch).not.toHaveBeenCalled();expect(write).not.toHaveBeenCalled()}finally{fetch.mockRestore()}})
