import { useState } from 'react'
import { applyAiEditorProposal, buildAiEditorContext, describeAiEdit, parseAiEditorProposal, type AiEditorProposal } from '../core/aiEditor'
import type { KinaouProject } from '../core/project'
import type { PersistentVersionHistory } from '../core/versioning'
import { WorkerClient } from '../core/workerClient'

interface Props { project: KinaouProject; history: PersistentVersionHistory; workerUrl: string; workerToken: string; workerConnected: boolean; workerCapabilities: string[]; onProjectChange: (project: KinaouProject) => void }

export function AiEditorPanel({ project, history, workerUrl, workerToken, workerConnected, workerCapabilities, onProjectChange }: Props) {
  const [source, setSource] = useState(''); const [proposal, setProposal] = useState<AiEditorProposal | null>(null); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState('')
  const [models, setModels] = useState<Array<{ id: string; sizeBytes: number }>>([]); const [model, setModel] = useState(''); const [instruction, setInstruction] = useState(''); const [busy, setBusy] = useState(false)
  function accept(next: AiEditorProposal, success: string) { next.operations.forEach((operation) => describeAiEdit(project, operation)); setProposal(next); setSelected([]); setSource(JSON.stringify(next, null, 2)); setMessage(success) }
  function review() { try { accept(parseAiEditorProposal(JSON.parse(source)), 'Proposal is valid. Select operations to apply.') } catch (error) { setProposal(null); setSelected([]); setMessage(error instanceof Error ? error.message : 'Invalid proposal') } }
  async function detectModels() { setBusy(true); try { const next = await new WorkerClient({ baseUrl: workerUrl, token: workerToken }).listLocalModels(); setModels(next); setModel(next[0]?.id ?? ''); setMessage(next.length ? 'Local models loaded.' : 'No local Ollama model is installed.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Model discovery failed') } finally { setBusy(false) } }
  async function generate() { setBusy(true); setProposal(null); setSelected([]); try { accept(parseAiEditorProposal(await new WorkerClient({ baseUrl: workerUrl, token: workerToken }).generateAiEditorProposal(model, instruction, buildAiEditorContext(project))), 'Local proposal passed schema and target validation. Select operations to apply.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Local proposal generation failed') } finally { setBusy(false) } }
  function apply() { if (!proposal || !selected.length) return; history.snapshot(project, `Before AI Editor: ${proposal.title}`, 'system'); onProjectChange(applyAiEditorProposal(project, proposal, selected)); setMessage(`${selected.length} operation(s) applied. The previous state is in Version History.`); setProposal(null); setSelected([]); setSource('') }
  return <div className="card aiEditorPanel"><div><div className="eyebrow">AI EDITOR</div><h3>Review structured timeline changes</h3><p>Nothing changes until individual operations are selected and applied.</p></div><div className="localAiEditor"><label>Edit instruction<input value={instruction} onChange={(event) => setInstruction(event.target.value)} placeholder="Tighten pacing and soften the voice track" /></label><label>Local Ollama model<select value={model} onChange={(event) => setModel(event.target.value)}><option value="">Detect a model first</option>{models.map((item) => <option key={item.id} value={item.id}>{item.id}</option>)}</select></label><div className="directorActions"><button className="secondaryButton" disabled={busy || !workerConnected || !workerCapabilities.includes('local-llm')} onClick={detectModels}>Detect models</button><button className="primary" disabled={busy || !model || !instruction.trim()} onClick={generate}>{busy ? 'Working locally…' : 'Generate proposal locally'}</button></div></div><label>Editor proposal JSON<textarea value={source} onChange={(event) => { setSource(event.target.value); setProposal(null); setSelected([]); setMessage('') }} placeholder='{"schemaVersion":1,"title":"…","objective":"…","operations":[…],"provenance":{"kind":"manual"}}' /></label><div className="directorActions"><button className="secondaryButton" disabled={!source.trim()} onClick={review}>Validate and preview diff</button>{proposal && <button className="primary" disabled={!selected.length} onClick={apply}>Apply {selected.length} selected</button>}</div>{message && <div className={proposal ? 'note' : 'warning'}>{message}</div>}{proposal && <div className="aiDiffs">{proposal.operations.map((operation) => { const diff = describeAiEdit(project, operation); return <label key={operation.id}><input type="checkbox" checked={selected.includes(operation.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, operation.id] : current.filter((id) => id !== operation.id))} /><span><strong>{operation.reason}</strong><small>Before: {diff.before}</small><small>After: {diff.after}</small></span></label> })}</div>}</div>
}
