import { useEffect, useRef, useState } from 'react'
import { frameAnnotationPoint, frameMarkSchema, loadFrameBitmap, newFrameMark, paintFrameAnnotations, rasterizeFrameAnnotations, type AnnotatedFrame, type FrameMark, type SourceFrame } from '../core/frameAnnotations'
import { useUiLanguage } from './UiLanguageProvider'

export function FrameAnnotationEditor({frame,disabled,onChange,onReviewed}:{frame:SourceFrame;disabled:boolean;onChange:()=>void;onReviewed:(value:AnnotatedFrame)=>void}) {
 const {t}=useUiLanguage(),canvas=useRef<HTMLCanvasElement>(null),mounted=useRef(true),flight=useRef(false)
 const [bitmap,setBitmap]=useState<ImageBitmap|null>(null),[edits,setEdits]=useState<FrameMark[][]>([[]]),[position,setPosition]=useState(0),[selected,setSelected]=useState(''),[target,setTarget]=useState<'start'|'end'>('start'),[preparing,setPreparing]=useState(false),[error,setError]=useState('')
 const marks=edits[position],mark=marks.find(m=>m.id===selected)??marks[0],locked=disabled||preparing
 useEffect(()=>{mounted.current=true;let current=true,image:ImageBitmap|undefined;void loadFrameBitmap(frame).then(value=>{if(!current){value.close();return}image=value;setBitmap(value)},cause=>{if(current)setError(String(cause))});return()=>{current=false;mounted.current=false;image?.close()}},[frame])
 useEffect(()=>{if(!bitmap||!canvas.current)return;const ctx=canvas.current.getContext('2d');if(!ctx){setError('Canvas unavailable');return}ctx.clearRect(0,0,bitmap.width,bitmap.height);ctx.drawImage(bitmap,0,0);try{paintFrameAnnotations(ctx,bitmap.width,bitmap.height,marks);setError('')}catch(cause){setError(String(cause))}},[bitmap,marks])
 function edit(next:FrameMark[]){if(locked)return;onChange();const history=[...edits.slice(0,position+1),structuredClone(next)].slice(-100);setEdits(history);setPosition(history.length-1);setError('')}
 function patch(change:Partial<FrameMark>){if(!mark||locked)return;try{edit(marks.map(m=>m.id===mark.id?frameMarkSchema.parse({...m,...change}):m))}catch(cause){setError(String(cause))}}
 function point(x:number,y:number){patch(mark?.kind==='label'||target==='start'?{x1:x,y1:y}:{x2:x,y2:y})}
 async function prepare(){if(locked||flight.current||!marks.length||!bitmap)return;flight.current=true;setPreparing(true);setError('');try{const value=await rasterizeFrameAnnotations(frame,marks);if(mounted.current)onReviewed(value)}catch(cause){if(mounted.current)setError(String(cause))}finally{flight.current=false;if(mounted.current)setPreparing(false)}}
 return <section className="stack frameAnnotationEditor"><h4>{t('frameMarks.heading')}</h4><p>{t('frameMarks.help')}</p>
  <canvas ref={canvas} width={frame.record.width} height={frame.record.height} className="frameAnnotationCanvas" tabIndex={0} aria-label={t('frameMarks.canvas')} onClick={e=>{if(locked||!mark)return;const p=frameAnnotationPoint(e.clientX,e.clientY,e.currentTarget.getBoundingClientRect());point(p.x,p.y)}} onKeyDown={e=>{if(locked||!mark||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const start=mark.kind==='label'||target==='start',x=start?mark.x1:mark.x2,y=start?mark.y1:mark.y2,step=e.shiftKey?0.1:1;point(Math.max(0,Math.min(100,x+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0))),Math.max(0,Math.min(100,y+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0))))}}/>
  <div className="renderActions">{(['arrow','box','label'] as const).map(kind=><button key={kind} className="secondaryButton" disabled={locked||marks.length>=16} onClick={()=>{const value=newFrameMark(kind,t('frameMarks.defaultText'));edit([...marks,value]);setSelected(value.id)}}>{t(`frameMarks.add.${kind}`)}</button>)}</div>
  <label>{t('frameMarks.select')}<select disabled={locked||!marks.length} value={mark?.id??''} onChange={e=>setSelected(e.target.value)}>{!marks.length&&<option value="">—</option>}{marks.map((m,i)=><option key={m.id} value={m.id}>{i+1} · {t(`frameMarks.${m.kind}`)}{m.kind==='label'?` · ${m.text}`:''}</option>)}</select></label>
  {mark&&<><div className="formRow"><label>{t('frameMarks.color')}<select disabled={locked} value={mark.color} onChange={e=>patch({color:e.target.value as FrameMark['color']})}>{(['yellow','red','white'] as const).map(c=><option key={c} value={c}>{t(`frameMarks.${c}`)}</option>)}</select></label><label>{t('frameMarks.point')}<select disabled={locked||mark.kind==='label'} value={mark.kind==='label'?'start':target} onChange={e=>setTarget(e.target.value as typeof target)}><option value="start">{t('frameMarks.start')}</option><option value="end">{t('frameMarks.end')}</option></select></label></div>
   {mark.kind==='label'&&<label>{t('frameMarks.text')}<input maxLength={40} disabled={locked} value={mark.text} onChange={e=>patch({text:e.target.value})}/></label>}
   <div className="mediaExcerptFields">{(['x1','y1','x2','y2'] as const).map(key=><label key={key}>{t(`frameMarks.${key}`)}<input type="number" min={0} max={100} step={0.1} disabled={locked||(mark.kind==='label'&&['x2','y2'].includes(key))} value={mark[key]} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))patch({[key]:e.target.valueAsNumber})}}/></label>)}</div>
   <button className="secondaryButton" disabled={locked} onClick={()=>edit(marks.filter(m=>m.id!==mark.id))}>{t('frameMarks.remove')}</button></>}
  <div className="renderActions"><button className="secondaryButton" disabled={locked||position===0} onClick={()=>{onChange();setPosition(position-1)}}>{t('tactics.undo')}</button><button className="secondaryButton" disabled={locked||position===edits.length-1} onClick={()=>{onChange();setPosition(position+1)}}>{t('tactics.redo')}</button><button className="secondaryButton" disabled={locked||!marks.length} onClick={()=>edit([])}>{t('frameMarks.clear')}</button></div>
  <button className="secondaryButton" disabled={locked||!bitmap||!marks.length||!!error} onClick={()=>void prepare()}>{t(preparing?'frameMarks.preparing':'frameMarks.review')}</button>
  {error&&<div role="alert">{t('frameMarks.error')}<details><summary>{t('common.details')}</summary>{error}</details></div>}
 </section>
}
