import { courseOutlineSchema, type CourseOutline } from './course'
import { canExportCourseExercises } from './courseExercises'

export const courseWorkbookInstructions = {
  de: 'workbook.html ist das Offline-Arbeitsbuch aus den Lernmaterialien und Arbeitsblättern dieses Pakets. Nach dem Entpacken im Browser öffnen und vor Weitergabe prüfen. Bei Bedarf über die Druckfunktion des Browsers drucken oder mit vorhandener PDF-Option sichern. Kein PDF automatisch erzeugt; keine Lösungen in Lösungsfeldern, keine internen Materialien oder Skripte enthalten.',
  en: 'workbook.html is the offline workbook made from this package’s learner materials and worksheets. Extract, open in a browser and review before sharing. Use the browser’s print function to print or save through an available PDF option. No PDF generated automatically; no solution fields, internal materials or scripts included.',
  fr: 'workbook.html est le cahier hors ligne issu des ressources et fiches de ce dossier apprenant. Décompressez, ouvrez dans un navigateur et vérifiez avant diffusion. Utilisez son impression ou son option PDF si disponible. Aucun PDF créé automatiquement ; aucun champ de solution, document interne ou script inclus.'
} as const

const labels = {
  de: { title: 'Arbeitsbuch für Lernende', draft: 'ENTWURF · vor Weitergabe fachlich prüfen', contents: 'Inhalt', revision: 'Kursrevision', materials: 'Lernmaterialien', exercises: 'Übungen', hint: 'Hinweis', answer: 'Deine Notizen / Antwort', back: 'Zurück zum Inhalt', help: 'Nur gespeicherte Lernmaterialien und Aufgaben. Keine Lösungsfelder, internen Materialien, Skripte oder Prüfnotizen. Eigene Hinweise und Materialien können dennoch Antworten oder private Angaben enthalten: vor Weitergabe prüfen. Keine Videos, externen Dateien oder Plattformfreigabe. Offline im Browser lesbar; über dessen Druckfunktion ausdrucken oder bei vorhandener PDF-Option als PDF sichern. Keine PDF-Datei wird automatisch erzeugt.' },
  en: { title: 'Learner workbook', draft: 'DRAFT · expert review required before sharing', contents: 'Contents', revision: 'Course revision', materials: 'Learning materials', exercises: 'Exercises', hint: 'Hint', answer: 'Your notes / answer', back: 'Back to contents', help: 'Saved learner materials and tasks only. No answer fields, internal materials, scripts or review notes. Authored hints and materials can still contain answers or private information: review before sharing. No videos, external files or platform approval. Read offline in a browser; use its print function to print or save as PDF where available. No PDF file is generated automatically.' },
  fr: { title: 'Cahier de l’apprenant', draft: 'BROUILLON · vérification experte avant diffusion', contents: 'Sommaire', revision: 'Révision du cours', materials: 'Ressources pédagogiques', exercises: 'Exercices', hint: 'Indice', answer: 'Vos notes / réponse', back: 'Retour au sommaire', help: 'Uniquement les ressources et énoncés enregistrés pour les apprenants. Aucun champ de réponse, document interne, script ou note de vérification. Les indices et ressources peuvent toutefois contenir des réponses ou informations privées : vérifiez avant diffusion. Ni vidéos, ni fichiers externes, ni approbation de plateforme. Lecture hors ligne dans un navigateur ; utilisez son impression ou son option PDF si disponible. Aucun PDF n’est créé automatiquement.' }
} as const

function escape(text: string): string {
  if (text.includes('\0') || new TextDecoder('utf-8', { fatal: true, ignoreBOM: true }).decode(new TextEncoder().encode(text)) !== text) throw Error('Workbook contains unrepresentable text')
  return text.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!)
}

/** Fixed markup only: authored strings are text, never HTML/Markdown/URLs. No scripts or remote assets. */
export function createCourseLearnerWorkbook(value: CourseOutline): string {
  const course = courseOutlineSchema.parse(value), t = labels[course.language]
  const modules = course.modules.map((module, m) => ({ module, m, lessons: module.lessons.map((lesson, l) => ({ lesson, l, materials: (lesson.materials ?? []).filter(item => item.audience === 'learner') })).filter(item => item.materials.length || item.lesson.exercises?.length) })).filter(item => item.lessons.length)
  if (!modules.length) throw Error('No saved learner workbook content')
  const toc = modules.map(({ module, m, lessons }) => `<li><strong>${m + 1}. ${escape(module.title)}</strong><ol>${lessons.map(({ lesson, l }) => `<li><a href="#lesson-${m}-${l}">${m + 1}.${l + 1} ${escape(lesson.title)}</a></li>`).join('')}</ol></li>`).join('')
  const body = modules.map(({ module, m, lessons }) => `<section class="module"><h2>${m + 1}. ${escape(module.title)}</h2>${lessons.map(({ lesson, l, materials }) => {
    if (materials.some(item => !item.body.trim())) throw Error('Empty learner workbook material')
    const exercises = lesson.exercises ?? []
    if (exercises.length && !canExportCourseExercises(exercises, 'worksheet')) throw Error('Incomplete learner workbook exercises')
    const resources = materials.length ? `<h4>${t.materials}</h4>${materials.map(item => `<section class="material"><h5>${escape(item.title)}</h5><div class="authored">${escape(item.body)}</div></section>`).join('')}` : ''
    const practice = exercises.length ? `<h4>${t.exercises}</h4>${exercises.map((item, i) => `<section class="exercise"><h5>${i + 1}. ${escape(item.title)}</h5><div class="authored">${escape(item.prompt)}</div>${item.hint.trim() ? `<p class="hint"><strong>${t.hint}</strong></p><div class="authored">${escape(item.hint)}</div>` : ''}<p class="answer-label">${t.answer}</p><div class="answer-space" aria-hidden="true"></div></section>`).join('')}` : ''
    return `<article id="lesson-${m}-${l}"><p class="eyebrow">${t.title} · ${m + 1}.${l + 1}</p><h3>${escape(lesson.title)}</h3>${resources}${practice}<a class="back" href="#contents">${t.back}</a></article>`
  }).join('')}</section>`).join('')
  return `<!doctype html>
<html lang="${course.language}"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="referrer" content="no-referrer"><title>${escape(course.title)} · ${t.title}</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#eef1f5;color:#182539;font:17px/1.6 system-ui,-apple-system,sans-serif}main{max-width:900px;margin:32px auto;background:white;padding:clamp(20px,5vw,64px);box-shadow:0 8px 40px #14274212}header{border-top:7px solid #46618c;padding-top:26px}h1{font-size:2.5rem;line-height:1.15;letter-spacing:-.04em;margin:20px 0}h2{font-size:1.8rem;border-bottom:2px solid #46618c;padding-bottom:12px;margin-top:56px}h3{font-size:1.5rem;line-height:1.3}h4{font-size:1.05rem;color:#46618c;margin-top:32px}h5{font-size:1rem;margin:20px 0 8px}.eyebrow{font-size:.8rem;letter-spacing:.08em;text-transform:uppercase;color:#46618c}.draft{display:inline-block;border:1px solid #b07020;padding:5px 10px;border-radius:4px;color:#785019;font-size:.8rem}.notice{font-size:.85rem;color:#465368}nav{background:#f4f6fa;padding:20px 26px;margin:32px 0}nav ol{list-style:none;padding-left:16px}nav>ol{padding:0}nav li{margin:8px 0}a{color:#304e7f;text-decoration-thickness:1px;text-underline-offset:3px}a:focus-visible{outline:3px solid #b07020;outline-offset:4px}article{padding:12px 0 36px;border-bottom:1px solid #cbd3e0;scroll-margin-top:24px}.authored{white-space:pre-wrap;overflow-wrap:anywhere;tab-size:4}.hint,.answer-label{font-size:.85rem;color:#465368}.answer-space{height:100px;border:1px solid #cbd3e0;border-radius:5px;margin:8px 0 24px}.back{display:inline-block;margin-top:20px;font-size:.85rem}h1,h2,h3,h4,h5,a{overflow-wrap:anywhere}h2,h3,h4,h5{break-after:avoid}p,.authored{orphans:3;widows:3}@page{margin:18mm}@media print{body{background:white;font-size:11pt}main{max-width:none;margin:0;padding:0;box-shadow:none}nav{background:white;border:1px solid #cbd3e0}article{break-before:page}h1{font-size:28pt}h2{font-size:21pt}h3{font-size:18pt}.back{display:none}.answer-space{height:30mm;break-inside:avoid}a{color:inherit;text-decoration:none}.module{break-before:page}.module>article:first-of-type{break-before:auto}}
</style></head><body><main><header><p class="eyebrow">KINAOU · ${t.title}</p><h1>${escape(course.title)}</h1><p>${t.revision}: ${course.revision}</p><p class="draft">${t.draft}</p><p class="notice">${t.help}</p></header><nav id="contents" aria-label="${t.contents}"><h2>${t.contents}</h2><ol>${toc}</ol></nav>${body}<footer><p class="notice">${t.draft} · KINAOU</p></footer></main></body></html>`
}
