export const uiAvailabilityMessages = {
  'availability.eyebrow': ["MEDIENVERFÜGBARKEIT","MEDIA AVAILABILITY","DISPONIBILITÉ DES MÉDIAS"],
  'availability.heading': ["Sind die verwalteten Dateien noch vorhanden?","Are managed files still present?","Les fichiers gérés sont-ils toujours présents ?"],
  'availability.help': ["Prüft, ob die verwalteten Pfade auf nicht leere Dateien zeigen. Fehlende Medien werden im Projekt als offline markiert und vom Rendern ausgeschlossen; gefundene wieder freigegeben. Es werden keine Dateien verändert. Dies prüft weder Inhalt, Unverändertheit noch Qualität. Das Ergebnis gilt zum Prüfzeitpunkt.","Checks whether managed paths point to nonempty files. Missing media are marked offline in the project and blocked from rendering; found files are enabled again. No files are changed. This checks neither content, integrity nor quality. Results apply at the check time.","Vérifie si les chemins gérés désignent des fichiers non vides. Les médias absents sont marqués hors ligne dans le projet et exclus du rendu ; ceux retrouvés sont réactivés. Aucun fichier n’est modifié. Ce contrôle ne vérifie ni contenu, ni intégrité, ni qualité. Le résultat vaut au moment du contrôle."],
  'availability.scope': ["Änderungen am Projekt oder an der Verbindung und Verlassen verwerfen verspätete Antworten. Statusänderungen werden erst nach vollständiger Prüfung und einer Sicherheitsversion gespeichert. Wiederherstellen von Statusmarkierungen ersetzt keine neue Dateiprüfung.","Project or connection changes and leaving discard late replies. Status changes are saved only after a complete check and a safety version. Restoring status flags does not replace a fresh file check.","Les changements de projet ou de connexion et la fermeture ignorent les réponses tardives. Les changements de statut ne sont enregistrés qu’après un contrôle complet et une version de sécurité. Restaurer des statuts ne remplace pas un nouveau contrôle."],
  'availability.check': ["Medienverfügbarkeit prüfen","Check media availability","Vérifier la disponibilité des médias"],
  'availability.checking': ["Dateien werden geprüft …","Checking files…","Vérification des fichiers…"],
  'availability.empty': ["Noch keine verwalteten Medien zu prüfen.","No managed media to check yet.","Aucun média géré à vérifier."],
  'availability.succeeded': ["Prüfergebnis gespeichert bzw. ohne Statusänderung bestätigt.","Check result saved or confirmed with no status changes.","Résultat enregistré ou confirmé sans changement de statut."],
  'availability.summary': ["{checked} Medien geprüft · {wentOffline} jetzt offline · {cameOnline} wieder verfügbar · {offline} insgesamt offline","{checked} assets checked · {wentOffline} now offline · {cameOnline} back online · {offline} offline in total","{checked} médias vérifiés · {wentOffline} désormais hors ligne · {cameOnline} retrouvés · {offline} hors ligne au total"],
  'availability.time': ["Geprüft: {time}","Checked: {time}","Vérifié : {time}"],
  'availability.failed': ["Prüfung oder Speicherung fehlgeschlagen. Es wird kein vollständiger Erfolg behauptet; eine Sicherheitsversion kann bereits existieren. Erneut prüfen liest die Dateien neu.","Check or save failed. No complete success is claimed; a safety version may already exist. Checking again reads the files afresh.","Échec du contrôle ou de l’enregistrement. Aucun succès complet n’est affirmé ; une version de sécurité peut déjà exister. Relancer lit à nouveau les fichiers."],
  'availability.detached': ["Prüfung verworfen, weil sich der Kontext geändert hat. Erneut prüfen.","Check discarded because its context changed. Check again.","Contrôle ignoré car le contexte a changé. Relancez la vérification."],
} satisfies Record<string, readonly [string, string, string]>
