export const uiCourseExportMessages = {
  'lessonExport.heading': ['Kurslektionen exportieren', 'Course lesson export', 'Exporter les leçons du cours'],
  'lessonExport.count': ['Gespeicherte Lektionen: {count}', 'Saved lessons: {count}', 'Leçons enregistrées : {count}'],
  'lessonExport.help': ['Eine Lektion auszuwählen bereitet nur ihren Bereich vor. Prüfe Format und Ton und starte den Videoexport ausdrücklich, um eine eigene MP4 zu erstellen. Schnittänderungen verschieben gespeicherte Lektionsgrenzen nicht automatisch.', 'Choosing a lesson only prepares its range. Review format and sound, then explicitly start video export to create a separate MP4. Timeline edits do not automatically move saved lesson boundaries.', 'Choisir une leçon prépare seulement sa plage. Vérifiez le format et le son, puis lancez explicitement l’export vidéo pour créer un MP4 distinct. Les modifications du montage ne déplacent pas automatiquement les limites enregistrées.'],
  'lessonExport.select': ['Gespeicherte Lektion', 'Saved lesson', 'Leçon enregistrée'],
  'lessonExport.none': ['Keine Kurslektion ausgewählt', 'No course lesson selected', 'Aucune leçon sélectionnée'],
  'lessonExport.receipt': ['Der Exportbeleg behält die eingereichten Kurs-, Modul- und Lektionsnamen sowie die Gliederungsversion. Das bestätigt weder eine fachliche Prüfung noch eine Plattformzulassung.', 'The export receipt retains submitted course/module/lesson names and outline revision. This does not establish academic review or platform approval.', 'Le reçu conserve les noms du cours, module et leçon envoyés et la révision du plan. Cela ne prouve ni validation pédagogique ni approbation par une plateforme.'],
  'lessonExport.error': ['Gespeicherte Kursgliederung nicht lesbar. Stelle eine gültige Version wieder her. Ein eigener Exportbereich bleibt unabhängig nutzbar.', 'Saved course outline could not be read. Restore a valid version. A custom export range remains independently usable.', 'Le plan enregistré est illisible. Restaurez une version valide. Une plage d’export personnalisée reste utilisable indépendamment.'],
  'lessonExport.stale': ['Die ausgewählte Lektion, ihre Gliederung oder ihr Bereich hat sich geändert. Export gesperrt: Prüfe die aktuelle Lektion erneut oder hebe die Lektionsauswahl ausdrücklich auf.', 'The selected lesson, outline or range changed. Export is blocked: review the current lesson again or explicitly clear the lesson selection.', 'La leçon sélectionnée, son plan ou sa plage a changé. Export bloqué : revérifiez la leçon actuelle ou retirez explicitement la sélection.'],
  'lessonExport.unavailable': ['Frühere Auswahl nicht mehr verfügbar', 'Previous selection no longer available', 'Sélection précédente indisponible'],
  'lessonExport.review': ['Aktuelle Lektion erneut übernehmen', 'Review current lesson again', 'Reprendre la leçon actuelle'],
  'lessonExport.clear': ['Lektionsauswahl aufheben', 'Clear lesson selection', 'Retirer la sélection de leçon'],
  'range.milliseconds': ['Start und Ende müssen ganze Millisekunden ergeben.', 'In and Out must resolve to whole milliseconds.', 'Le début et la fin doivent correspondre à des millisecondes entières.'],
  'range.beforeStart': ['Start darf nicht vor dem Timeline-Anfang liegen.', 'In cannot be before the start of the timeline.', 'Le début ne peut pas précéder la timeline.'],
  'range.order': ['Ende muss nach Start liegen.', 'Out must be later than In.', 'La fin doit suivre le début.'],
  'range.afterEnd': ['Ende darf nicht hinter dem Timeline-Ende liegen.', 'Out cannot be later than the end of the timeline.', 'La fin ne peut pas dépasser la timeline.']
} satisfies Record<string, readonly [string, string, string]>
