export const uiCoursePlaybackMessages = {
  'course.playback.heading': ['Gespeichertes Video ansehen / anhören', 'Watch / listen to retained video', 'Voir / écouter la vidéo conservée'],
  'course.playback.help': ['Lädt ausdrücklich die originale MP4 der ausgewählten Referenz in den Browser (höchstens 256 MiB). Kein Proxy, kein neuer Render, kein Autoplay, keine Dateiänderung und kein Upload. Größere Dateien im lokalen Player öffnen. Abspielen bestätigt weder den aktuellen Schnitt noch Kursqualität oder unveränderte Dateiinhalte; vollständig selbst ansehen und anhören.', 'Explicitly loads the selected original MP4 into the browser (up to 256 MiB). No proxy, new render, autoplay, file change or upload. Open larger files in a local player. Playback does not confirm current edit, course quality or unchanged file contents; watch and listen fully yourself.', 'Charge explicitement le MP4 original sélectionné dans le navigateur (256 Mio maximum). Ni proxy, nouveau rendu, lecture automatique, modification ni envoi. Ouvrez les fichiers plus grands dans un lecteur local. La lecture ne valide ni montage actuel, qualité ni fichier inchangé ; visionnez et écoutez vous-même.'],
  'course.playback.unavailable': ['Lokalen Worker mit Lektionswiedergabe verbinden (nach einem Worker-Update neu starten und verbinden).', 'Connect a local worker with lesson playback (restart and reconnect after a worker update).', 'Connectez un worker local avec lecture des leçons (redémarrez et reconnectez-le après mise à jour).'],
  'course.playback.load': ['Ausgewähltes Video laden', 'Load selected video', 'Charger la vidéo sélectionnée'],
  'course.playback.loading': ['Originalvideo wird geladen…', 'Loading original video…', 'Chargement de la vidéo originale…'],
  'course.playback.loaded': ['Videodatei geladen. Wiedergabe mit den Player-Steuerelementen starten; noch keine Qualitätsfreigabe.', 'Video file loaded. Start playback using the player controls; this is not quality approval.', 'Fichier vidéo chargé. Lancez la lecture avec les commandes ; ce n’est pas une validation de qualité.'],
  'course.playback.failed': ['Video konnte nicht geladen oder vom Browser abgespielt werden. Verbindung, Datei, Größe und Codec prüfen; gegebenenfalls lokalen Player nutzen. Nur ausdrücklich erneut laden.', 'Video could not be loaded or decoded by the browser. Check connection, file, size and codec; use a local player if needed. Reload explicitly only.', 'Vidéo non chargée ou non décodée par le navigateur. Vérifiez connexion, fichier, taille et codec ; utilisez un lecteur local si nécessaire. Rechargez explicitement.'],
  'course.playback.detached': ['Wiedergabe verworfen: Projekt, Entwurf, Auswahl oder Verbindung geändert. Browserzugriff abgebrochen und temporäre Wiedergabeadresse freigegeben.', 'Playback discarded: project, draft, selection or connection changed. Browser read aborted and temporary playback address released.', 'Lecture écartée : projet, brouillon, choix ou connexion modifiés. Lecture réseau annulée et adresse temporaire libérée.'],
  'course.playback.player': ['Originales gespeichertes Lektionsvideo', 'Original retained lesson video', 'Vidéo originale de leçon conservée'],
  'course.playback.close': ['Video schließen / Laden abbrechen', 'Close video / cancel loading', 'Fermer la vidéo / annuler le chargement']
} as const
