export const uiCourseSubtitleMessages = {
  'course.subtitles.heading': ['Untertiteldatei pro Lektion', 'Subtitle file per lesson', 'Fichier de sous-titres par leçon'],
  'course.subtitles.help': ['WebVTT-Textdatei aus den sichtbaren Untertitelclips des aktuellen gespeicherten Schnitts. Zeitnull entspricht dem Lektionsanfang; angeschnittene Intervalle werden an Lektionsgrenzen begrenzt und unten ausgewiesen. Text bleibt vollständig. Keine Transkription, Übersetzung, Formatierungen oder Positionen exportiert.', 'WebVTT text file from visible caption clips in the current saved edit. Time zero is lesson start; intersecting intervals are bounded to lesson edges and reported below. Text stays complete. No transcription, translation, styling or positions exported.', 'Fichier texte WebVTT depuis les clips de sous-titres visibles du montage enregistré actuel. Zéro correspond au début de la leçon ; les intervalles sont bornés aux limites et signalés ci-dessous. Texte conservé intégralement. Ni transcription, traduction, styles ni positions exportés.'],
  'course.subtitles.boundary': ['Nicht automatisch mit einer früheren MP4 synchron: Video muss denselben Schnitt und Lektionsbereich verwenden. Sprache ist die Kursangabe, keine geprüfte Spracherkennung. Inhalt/Timing selbst prüfen. Kein Upload, keine Plattformfreigabe und keine Änderung am Projekt oder an Medien.', 'Not automatically synchronized with an earlier MP4: video must use the same edit and lesson range. Language is the course label, not verified detection. Review content/timing yourself. No upload, platform approval or project/media changes.', 'Pas de synchronisation automatique avec un ancien MP4 : la vidéo doit utiliser le même montage et la même plage. La langue est celle du cours, non une détection vérifiée. Vérifiez contenu et temps. Aucun envoi, agrément ni changement du projet ou des médias.'],
  'course.subtitles.review': ['Untertiteldatei prüfen', 'Review subtitle file', 'Examiner le fichier de sous-titres'],
  'course.subtitles.summary': ['{lesson} · {language} · Revision {revision} · {count} Untertitel · {duration} s · an Lektionsgrenzen begrenzte Intervalle: {clipped}.', '{lesson} · {language} · revision {revision} · {count} cues · {duration} s · intervals bounded to lesson edges: {clipped}.', '{lesson} · {language} · révision {revision} · {count} sous-titres · {duration} s · intervalles bornés aux limites : {clipped}.'],
  'course.subtitles.ack': ['Text, relative Zeiten und gegebenenfalls begrenzte Intervalle passen zu meinem Lektionsvideo.', 'Text, relative times and any bounded intervals match my lesson video.', 'Texte, temps relatifs et intervalles éventuellement bornés correspondent à ma vidéo de leçon.'],
  'course.subtitles.download': ['Geprüfte WebVTT-Datei herunterladen', 'Download reviewed WebVTT file', 'Télécharger le fichier WebVTT examiné'],
  'course.subtitles.started': ['Download ausgelöst. Datei im Downloadordner prüfen; Abschluss durch den Browser wird hier nicht bestätigt.', 'Download requested. Check your download folder; browser completion is not confirmed here.', 'Téléchargement demandé. Vérifiez le dossier de téléchargement ; sa fin n’est pas confirmée ici.'],
  'course.subtitles.failed': ['Datei nicht ausgeliefert. Prüfung bleibt für einen erneuten Versuch erhalten.', 'File was not delivered. Review remains available for retry.', 'Fichier non livré. Examen conservé pour réessayer.'],
  'course.subtitles.lesson': ['Gültige gespeicherte Kurslektion erforderlich.', 'A valid saved course lesson is required.', 'Une leçon de cours enregistrée valide est requise.'],
  'course.subtitles.captions': ['Keine sichtbaren Untertitel im Lektionsbereich. Zuerst im Studio erstellen oder Zeitbereich prüfen.', 'No visible captions in the lesson range. Create them in Studio first or check the range.', 'Aucun sous-titre visible dans la plage. Créez-en dans Studio ou vérifiez la plage.'],
  'course.subtitles.unsupported': ['Ungültiger, fehlender oder nicht unterstützter Untertitelclip. Spur und Medienzuordnung im Studio prüfen.', 'Invalid, missing or unsupported caption clip. Review track and asset assignment in Studio.', 'Clip de sous-titre invalide, absent ou non pris en charge. Vérifiez piste et média dans Studio.'],
  'course.subtitles.overlap': ['Untertitel überlappen. Für diese einfache Textdatei zuerst im Studio eindeutig ordnen; nichts wird ausgelassen.', 'Captions overlap. Resolve their order in Studio for this plain-text file; nothing is omitted.', 'Sous-titres chevauchants. Clarifiez leur ordre dans Studio pour ce fichier texte ; rien n’est omis.'],
  'course.subtitles.text': ['Ungültiger Text, Leerzeile oder Steuerzeichen im Untertitel. Im Caption Editor korrigieren; keine stillen Textverluste.', 'Invalid text, blank line or control character in a cue. Correct it in Caption Editor; no silent text loss.', 'Texte invalide, ligne vide ou caractère de contrôle. Corrigez dans l’éditeur ; aucune perte silencieuse.'],
  'course.subtitles.limit': ['Dateilimit überschritten: 1.000 Untertitel oder 1 MiB. Kleinere Lektion ausdrücklich wählen; kein Teil-Download.', 'File limit exceeded: 1,000 cues or 1 MiB. Explicitly choose a smaller lesson; no partial download.', 'Limite dépassée : 1 000 sous-titres ou 1 Mio. Choisissez explicitement une leçon plus courte ; aucun téléchargement partiel.'],
  'course.subtitles.stale': ['Projekt, Lektionswahl oder Entwurf geändert. Erneut prüfen und bestätigen.', 'Project, lesson selection or draft changed. Review and acknowledge again.', 'Projet, leçon ou brouillon modifiés. Réexaminez et confirmez.']
} as const
