export const uiCourseNarrationMessages = {
  'course.narration.heading': ['Gespeicherte Lektion vertonen', 'Narrate a saved lesson', 'Mettre en voix une leçon enregistrée'],
  'course.narration.open': ['Audio-Studio für Lektionsvertonung öffnen', 'Open Audio Studio for lesson narration', 'Ouvrir le studio audio pour les leçons'],
  'course.narration.help': ['Wähle ein gespeichertes Lektionsskript und lade es ausdrücklich in den Textentwurf. Das ersetzt den bisherigen Entwurf, startet aber noch keine Vertonung. Wähle eine installierte passende Stimme und starte selbst. Kein Übersetzen, automatisches Platzieren, Untertiteln oder fachliches Prüfen. Bestehende Kursdaten, Timeline und Aufnahmen bleiben unverändert.', 'Select a saved lesson script and explicitly load it into the text draft. This replaces the previous draft but does not start synthesis. Choose a matching installed voice and start explicitly. No translation, automatic placement, captions or expert review. Existing course data, timeline and recordings stay unchanged.', 'Choisissez un script de leçon enregistré et chargez-le explicitement dans le brouillon. Cela remplace le texte précédent sans lancer la synthèse. Choisissez une voix installée adaptée et démarrez explicitement. Aucune traduction, insertion automatique, création de sous-titres ou validation experte. Cours, timeline et prises existantes restent intacts.'],
  'course.narration.lesson': ['Lektionsskript als Quelle', 'Lesson script source', 'Script de leçon source'],
  'course.narration.choose': ['Gespeicherte Lektion wählen', 'Choose a saved lesson', 'Choisir une leçon enregistrée'],
  'course.narration.load': ['Lektionsskript in Textentwurf laden', 'Load lesson script into text draft', 'Charger le script dans le brouillon'],
  'course.narration.clear': ['Quellenbindung lösen (als freien Text nutzen)', 'Clear source binding (use as free text)', 'Retirer le lien source (texte libre)'],
  'course.narration.bound': ['Quelle gebunden: {lesson} · Kursrevision {revision} · Sprache {language}. Führende und abschließende Leerzeichen werden für die Vertonung entfernt. Stimme und Ergebnis bitte selbst anhören.', 'Bound source: {lesson} · course revision {revision} · language {language}. Leading and trailing whitespace is trimmed for synthesis. Audition the voice and result yourself.', 'Source liée : {lesson} · révision {revision} · langue {language}. Les espaces de début et fin sont retirés pour la synthèse. Écoutez vous-même la voix et le résultat.'],
  'course.narration.blocked': ['Quelle, Text oder Sprache stimmen nicht überein. Gespeichertes Skript erneut laden, passende Sprache/Stimme wählen oder Quellenbindung ausdrücklich lösen. Keine automatische Übersetzung.', 'Source, text or language no longer matches. Reload the saved script, select a matching voice/language or explicitly clear its binding. No automatic translation.', 'Source, texte ou langue non concordants. Rechargez le script, choisissez une voix/langue adaptée ou retirez explicitement le lien. Aucune traduction automatique.'],
  'course.narration.invalid': ['Kursquelle konnte nicht gelesen werden. Freie Vertonung bleibt möglich; beschädigte Kursdaten über die Versionshistorie prüfen.', 'Could not read the course source. Free-text synthesis remains available; check damaged course data through Version History.', 'Impossible de lire la source du cours. La synthèse libre reste disponible ; vérifiez le cours endommagé via l’historique.'],
  'course.narration.empty': ['Noch keine gespeicherten Lektionsskripte verfügbar.', 'No saved lesson scripts available yet.', 'Aucun script de leçon enregistré disponible.'],
  'course.narration.asset': ['Vertont aus: {lesson} · Kursrevision {revision} · {language}. Herkunftsvermerk, keine Prüfung der gesprochenen Wörter oder Videoqualität.', 'Narrated from: {lesson} · course revision {revision} · {language}. Source attribution, not verification of spoken words or video quality.', 'Voix issue de : {lesson} · révision {revision} · {language}. Attribution de source, sans vérification des mots prononcés ni de la qualité vidéo.'],
  'course.narration.invalidAsset': ['Gespeicherter Kurs-Herkunftsvermerk ist ungültig.', 'Saved course source attribution is invalid.', 'L’attribution de source du cours est invalide.']
} as const
