export const uiCourseMaterialMessages = {
  'course.package.workbook': ['Das Lernenden-ZIP enthält zusätzlich workbook.html: ein Offline-Arbeitsbuch mit Inhaltsverzeichnis, Materialien, Übungen und Platz für Antworten. Nach dem Entpacken im Browser öffnen und prüfen; über dessen Druckfunktion bei Bedarf drucken oder als PDF sichern. Kein automatisch erzeugtes PDF, kein Upload. Eigene Textfelder können private Angaben oder Antworten enthalten.', 'The learner ZIP also includes workbook.html: an offline workbook with contents, materials, exercises and answer space. Extract, open in a browser and review; use its print function to print or save as PDF if needed. No automatically generated PDF or upload. Authored text fields can contain private information or answers.', 'Le ZIP apprenant contient aussi workbook.html : un cahier hors ligne avec sommaire, ressources, exercices et espaces de réponse. Décompressez, ouvrez dans un navigateur et vérifiez ; utilisez son impression ou son option PDF si nécessaire. Aucun PDF créé automatiquement ni téléversement. Les textes rédigés peuvent contenir des informations privées ou réponses.'],
  'course.materials.heading': ['Unterrichtsmaterialien', 'Lesson materials', 'Ressources pédagogiques'],
  'course.materials.help': ['Eigene Textmaterialien mit der Kursgliederung speichern. Wähle ausdrücklich, ob sie für Lernende oder nur für dich als Dozent bestimmt sind. Keine automatische fachliche Prüfung; vorhandene Medien werden weder kopiert noch verändert.', 'Save authored text materials with the outline. Explicitly choose learner or instructor-only visibility. No automatic expert review; existing media are not copied or modified.', 'Enregistrez vos ressources textuelles avec le plan. Choisissez explicitement la visibilité apprenant ou formateur uniquement. Aucune validation experte automatique ; les médias existants ne sont ni copiés ni modifiés.'],
  'course.materials.item': ['Material', 'Material', 'Ressource'],
  'course.materials.title': ['Materialtitel', 'Material title', 'Titre de la ressource'],
  'course.materials.audience': ['Bestimmt für', 'Intended for', 'Destinataire'],
  'course.materials.learner': ['Lernende', 'Learners', 'Apprenants'],
  'course.materials.instructor': ['Nur Dozent (intern)', 'Instructor only (internal)', 'Formateur uniquement (interne)'],
  'course.materials.body': ['Materialtext', 'Material text', 'Texte de la ressource'],
  'course.materials.add': ['Textmaterial hinzufügen', 'Add text material', 'Ajouter une ressource textuelle'],
  'course.materials.remove': ['Material aus Entwurf entfernen', 'Remove material from draft', 'Retirer la ressource du brouillon'],
  'course.package.heading': ['Kursmaterialien gesammelt herunterladen', 'Download course materials together', 'Télécharger les ressources du cours ensemble'],
  'course.package.help': [
    'ZIP-Dateien aus gespeicherten Texten, keine Videos oder externen Dateien. Das Lernendenpaket enthält Lernmaterialien und Arbeitsblätter, nicht Lösungsfelder, Skripte, interne Materialien oder Prüfnotizen. Prüfe trotzdem selbst, ob eigene Hinweise/Materialtexte Antworten enthalten. Leere ausgewählte Materialien und unvollständige Übungen blockieren den Download. Beide Pakete sind Entwürfe, nicht verschlüsselt und keine vollständigen Projektbackups.',
    'ZIP files of saved text, not videos or external files. The learner package includes learner materials and worksheets, not answer fields, scripts, internal materials or review notes. Still check authored hints/materials for answers yourself. Empty selected materials and incomplete exercises block the download. Both packages are drafts, unencrypted and not full project backups.',
    'Archives ZIP de textes enregistrés, sans vidéos ni fichiers externes. Le dossier apprenant contient ressources et fiches, sans champs de réponse, scripts, documents internes ni notes de vérification. Vérifiez toutefois si vos indices/ressources révèlent des réponses. Les ressources sélectionnées vides et exercices incomplets bloquent le téléchargement. Les deux dossiers sont des brouillons non chiffrés, pas des sauvegardes complètes.'
  ],
  'course.package.learner': ['Lernendenpaket als ZIP herunterladen', 'Download learner ZIP', 'Télécharger le ZIP apprenant'],
  'course.package.instructor': ['Privates Dozentenpaket als ZIP herunterladen', 'Download private instructor ZIP', 'Télécharger le ZIP privé du formateur'],
  'course.package.privateAck': ['Das Dozentenpaket enthält Lösungen und interne Notizen; ich gebe es nicht ungeprüft an Lernende weiter.', 'The instructor package contains answers and internal notes; I will not share it with learners without review.', 'Le dossier formateur contient réponses et notes internes ; je ne le diffuserai pas aux apprenants sans vérification.'],
  'course.package.failed': ['Materialpaket konnte nicht erstellt oder heruntergeladen werden.', 'Could not create or download the material package.', 'Impossible de créer ou télécharger le dossier de ressources.'],
  'course.package.changed': ['Projekt oder Entwurf geändert; kein veraltetes Paket heruntergeladen. Erneut prüfen.', 'Project or draft changed; no stale package downloaded. Review again.', 'Projet ou brouillon modifié ; aucun dossier obsolète téléchargé. Vérifiez à nouveau.'],
  'course.package.requested': ['Download angefordert: {filename}. Prüfe die Datei im Download-Ordner; kein Upload erfolgt.', 'Download requested: {filename}. Check your download folder; nothing was uploaded.', 'Téléchargement demandé : {filename}. Vérifiez le dossier des téléchargements ; rien n’a été publié.'],
  'course.package.busy': ['Materialpaket wird erstellt …', 'Creating material package…', 'Création du dossier de ressources…']
} as const
