export const uiFrameRevisionMessages={
 'frameRevision.heading':['Markierungen als neue Bildversion bearbeiten','Edit annotations as a new image version','Modifier les annotations dans une nouvelle version'],
 'frameRevision.help':['Gespeicherte Markierungen laden, dann das ursprüngliche Videoframe ausdrücklich erneut lesen. Nur wenn dessen PNG-Prüfsumme und Messdaten übereinstimmen, werden die Markierungen übernommen. Danach bearbeiten, das neue PNG prüfen und separat speichern. Vorheriges Bild, Quelle und Timeline bleiben unverändert. Die vollständige Videodatei und das alte Ergebnis-PNG werden dabei nicht neu gehasht.','Load saved annotations, then explicitly read the original video frame again. Annotations are applied only if its PNG checksum and measurements match. Then edit, review the new PNG and save separately. Previous image, source and timeline stay unchanged. This does not rehash the entire video or the previous output PNG.','Chargez les annotations enregistrées, puis relisez explicitement l’image vidéo originale. Les annotations sont reprises seulement si son empreinte PNG et ses mesures correspondent. Modifiez, examinez le nouveau PNG et enregistrez-le séparément. Image précédente, source et timeline restent inchangées. Cela ne recalcule pas l’empreinte de toute la vidéo ni de l’ancien PNG final.'],
 'frameRevision.open':['Gespeicherte Vorlage laden','Load saved template','Charger le modèle enregistré'],
 'frameRevision.read':['Originalframe für neue Version prüfen','Check original frame for new version','Vérifier l’image originale pour la nouvelle version'],
 'frameRevision.fixedTime':['Der gespeicherte Quellzeitpunkt bleibt für diese Vorlage fest. Erst das Originalframe erneut prüfen, dann Markierungen bearbeiten. Ein anderer Zeitpunkt benötigt ein neues Standbild.','The saved source time stays fixed for this template. Check the original frame again before editing annotations. A different time requires a new still frame.','L’instant source enregistré reste fixe pour ce modèle. Revérifiez l’image originale avant de modifier les annotations. Un autre instant nécessite une nouvelle image fixe.'],
 'frameRevision.error':['Die gespeicherte Vorlage passt nicht mehr zur verfügbaren Originalquelle. Originaleintrag wiederherstellen oder bewusst ein neues Standbild erstellen; alte Markierungen werden nicht automatisch übernommen.','The saved template no longer matches the available original source. Restore the original record or explicitly create a new still; old annotations are not applied automatically.','Le modèle enregistré ne correspond plus à la source originale disponible. Restaurez l’entrée originale ou créez explicitement une nouvelle image ; les anciennes annotations ne sont pas reprises automatiquement.'],
 'frameRevision.parent':['Vorherige Bildversion (gespeicherter Verweis, nicht neu dateigeprüft)','Previous image version (retained reference, not freshly file-verified)','Version d’image précédente (référence conservée, fichier non revérifié)'],
} as const
