export const uiSourceExcerptMessages={
 'sourceExcerpt.heading':['Kurzen Quellenbeleg übernehmen','Keep a short source excerpt','Conserver un court extrait source'],
 'sourceExcerpt.help':['Kopiere einen wortgetreuen Ausschnitt (höchstens 600 Zeichen) aus dem angezeigten Text hierher. Zunächst prüfen, dann ausdrücklich in den ungespeicherten Quellenvermerk übernehmen. Höchstens fünf unterschiedliche Zitate pro Vermerk; keine vollständigen Artikel.','Copy an exact excerpt (at most 600 characters) from the displayed text here. Review first, then explicitly add it to the unsaved assessment. At most five distinct excerpts per assessment; no full articles.','Copiez ici un extrait exact (600 caractères maximum) du texte affiché. Examinez-le, puis ajoutez-le explicitement à l’appréciation non enregistrée. Cinq extraits distincts maximum par appréciation ; aucun article complet.'],
 'sourceExcerpt.input':['Wortgetreues Zitat','Exact quotation','Citation exacte'],
 'sourceExcerpt.prepare':['Zitat und Herkunft prüfen','Review quotation and source','Examiner la citation et sa source'],
 'sourceExcerpt.ack':['Ich habe Wortlaut, Zusammenhang, Herkunft und zulässige Verwendung geprüft. Das Zitat ist kein Faktencheck und bestätigt keinen gelesenen Artikel.','I reviewed wording, context, attribution and permitted use. This excerpt is not a fact check and does not mark an article as read.','J’ai examiné formulation, contexte, attribution et utilisation permise. Cet extrait ne vérifie pas les faits et ne marque pas l’article comme lu.'],
 'sourceExcerpt.append':['Zum Vermerkentwurf hinzufügen','Add to assessment draft','Ajouter au brouillon d’appréciation'],
 'sourceExcerpt.added':['Im Entwurf, noch nicht gespeichert. Den gesamten Vermerk anschließend prüfen, bestätigen und speichern.','In the draft, not saved yet. Review, acknowledge and save the complete assessment next.','Dans le brouillon, pas encore enregistré. Examinez, confirmez puis enregistrez ensuite l’appréciation complète.'],
 'sourceExcerpt.failed':['Zitat nicht übernommen. Exakten Wortlaut, Quellenzuordnung, Duplikate und Grenze von fünf Zitaten prüfen.','Excerpt not added. Check exact wording, source binding, duplicates and the five-excerpt limit.','Extrait non ajouté. Vérifiez le texte exact, la source, les doublons et la limite de cinq extraits.'],
 'sourceExcerpt.savedHeading':['Ausgewählte Quellenzitate','Selected source excerpts','Extraits sources sélectionnés'],
 'sourceExcerpt.boundary':['Historischer Ausschnitt des extrahierten Texts, kein unabhängiger Wahrheits- oder Rechtebeleg. Vollständiger Artikel und HTML werden nicht gespeichert. Beim Speichern gehen diese Zitate mit Herkunft in den privaten Projektvermerk; ausdrücklich aktualisierte Briefings und ausgewählte Dossiers können sie ebenfalls enthalten.','Historical excerpt of extracted text, not independent proof of truth or rights. Full article and HTML are not saved. Saving includes these quotations and provenance in the private project assessment; explicitly refreshed briefs and selected dossiers may also contain them.','Extrait historique du texte extrait, pas une preuve indépendante de véracité ou de droits. L’article complet et le HTML ne sont pas enregistrés. L’enregistrement inclut citations et provenance dans l’appréciation privée ; les briefs explicitement actualisés et dossiers sélectionnés peuvent aussi les contenir.'],
 'sourceExcerpt.offsets':['Position im extrahierten Anzeigetext: {start}–{end} (UTF-16, Ende exklusiv); bei Wiederholungen erstes Vorkommen. Keine HTML-Byteposition.','Position in extracted display text: {start}–{end} (UTF-16, end exclusive); first occurrence if repeated. Not an HTML byte position.','Position dans le texte extrait affiché : {start}–{end} (UTF-16, fin exclusive) ; première occurrence si répétée. Pas une position en octets HTML.'],
 'sourceExcerpt.remove':['Zitat {index} aus Entwurf entfernen','Remove excerpt {index} from draft','Retirer l’extrait {index} du brouillon']
} as const
